#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "73e64d1ab73593b033a43d8616b739bdb639f9fe398d529fec7265485f8804a0"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (2,12)-(2,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
Microsoft.FluentUI.AspNetCore.Components.Charts

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (1,2)-(1,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
using Microsoft.FluentUI.AspNetCore.Components.Extensions

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentFunnelChart : 
#nullable restore
#line (3,11)-(3,26) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
FluentChartBase

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "fluent-funnel-chart");
            __builder.AddAttribute(1, "id", 
#nullable restore
#line (5,27)-(5,29) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
Id

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(2, "class", 
#nullable restore
#line (6,30)-(6,40) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
ClassValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(3, "style", 
#nullable restore
#line (7,30)-(7,40) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
StyleValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(4, "chart-title", 
#nullable restore
#line (8,36)-(8,46) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
ChartTitle

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(5, "data", 
#nullable restore
#line (9,29)-(9,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
ChartJson.Serialize(ChartData)

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(6, "width", 
#nullable restore
#line (10,30)-(10,35) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
Width

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(7, "height", 
#nullable restore
#line (11,31)-(11,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
Height

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(8, "hide-tooltip", 
#nullable restore
#line (12,38)-(12,65) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
HideTooltip ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(9, "hide-labels", 
#nullable restore
#line (13,37)-(13,63) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
HideLabels ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(10, "hide-legends", 
#nullable restore
#line (14,38)-(14,65) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
HideLegends ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(11, "round-corners", 
#nullable restore
#line (15,39)-(15,69) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
RoundedCorners ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(12, "legend-list-label", 
#nullable restore
#line (16,42)-(16,57) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
LegendListLabel

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(13, "allow-multiple-legend-selection", 
#nullable restore
#line (17,57)-(17,101) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
AllowMultipleLegendSelection ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(14, "culture", 
#nullable restore
#line (18,32)-(18,45) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
Culture?.Name

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(15, "orientation", 
#nullable restore
#line (19,36)-(19,66) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
Orientation.ToAttributeValue()

#line default
#line hidden
#nullable disable
            );
            __builder.AddMultipleAttributes(16, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (20,36)-(20,56) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
            __builder.CloseElement();
#nullable restore
#line (23,2)-(25,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
if (TooltipTemplate is not null)
{

#line default
#line hidden
#nullable disable

            __builder.OpenElement(17, "div");
            __builder.AddAttribute(18, "id", 
#nullable restore
#line (25,15)-(25,31) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
_tooltipPortalId

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(19, "style", "display:none;position:absolute;");
#nullable restore
#line (25,74)-(25,106) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
__builder.AddContent(20, TooltipTemplate(_tooltipContext)

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
#nullable restore
#line (26,1)-(27,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/FunnelChart/FluentFunnelChart.razor"
}

#line default
#line hidden
#nullable disable

        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
