#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "83391b8f75f86a3b374a18b486f96fc22b453ca6809ad23335a031ccae2245c7"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
Microsoft.FluentUI.AspNetCore.Components.Charts

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
using Microsoft.FluentUI.AspNetCore.Components.Extensions

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentAreaChart : 
#nullable restore
#line (3,11)-(3,35) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
FluentCartesianChartBase

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "fluent-area-chart");
            __builder.AddAttribute(1, "id", 
#nullable restore
#line (5,25)-(5,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
Id

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(2, "class", 
#nullable restore
#line (6,28)-(6,38) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
ClassValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(3, "style", 
#nullable restore
#line (7,28)-(7,38) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
StyleValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(4, "chart-title", 
#nullable restore
#line (8,34)-(8,44) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
ChartTitle

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(5, "data", 
#nullable restore
#line (9,27)-(9,57) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
ChartJson.Serialize(ChartData)

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(6, "width", 
#nullable restore
#line (10,28)-(10,33) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
Width

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(7, "height", 
#nullable restore
#line (11,29)-(11,35) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
Height

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(8, "hide-tooltip", 
#nullable restore
#line (12,36)-(12,63) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
HideTooltip ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(9, "hide-labels", 
#nullable restore
#line (13,35)-(13,61) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
HideLabels ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(10, "hide-legends", 
#nullable restore
#line (14,36)-(14,63) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
HideLegends ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(11, "legend-list-label", 
#nullable restore
#line (15,40)-(15,55) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
LegendListLabel

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(12, "show-y-axis-labels", 
#nullable restore
#line (16,42)-(16,73) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
ShowYAxisLabels ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(13, "show-y-axis-labels-tooltip", 
#nullable restore
#line (17,50)-(17,88) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
ShowYAxisLabelsTooltip ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(14, "enable-gradient", 
#nullable restore
#line (18,39)-(18,69) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
EnableGradient ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(15, "round-corners", 
#nullable restore
#line (19,37)-(19,67) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
RoundedCorners ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(16, "allow-multiple-legend-selection", 
#nullable restore
#line (20,55)-(20,99) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
AllowMultipleLegendSelection ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(17, "y-axis-category-order", 
#nullable restore
#line (21,44)-(21,81) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
YAxisCategoryOrder.ToAttributeValue()

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(18, "x-axis-tick-count", 
#nullable restore
#line (22,40)-(22,54) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
XAxisTickCount

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(19, "y-axis-tick-count", 
#nullable restore
#line (23,40)-(23,54) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
YAxisTickCount

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(20, "y-axis-padding", 
#nullable restore
#line (24,37)-(24,49) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
YAxisPadding

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(21, "x-min-value", 
#nullable restore
#line (25,34)-(25,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
XMinValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(22, "x-max-value", 
#nullable restore
#line (26,34)-(26,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
XMaxValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(23, "y-min-value", 
#nullable restore
#line (27,34)-(27,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
YMinValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(24, "y-max-value", 
#nullable restore
#line (28,34)-(28,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
YMaxValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(25, "x-axis-title", 
#nullable restore
#line (29,35)-(29,45) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
XAxisTitle

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(26, "y-axis-title", 
#nullable restore
#line (30,35)-(30,45) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
YAxisTitle

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(27, "x-axis-tick-format", 
#nullable restore
#line (31,41)-(31,56) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
XAxisTickFormat

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(28, "y-axis-tick-format", 
#nullable restore
#line (32,41)-(32,56) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
YAxisTickFormat

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(29, "tick-padding", 
#nullable restore
#line (33,35)-(33,46) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
TickPadding

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(30, "wrap-x-axis-labels", 
#nullable restore
#line (34,42)-(34,73) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
WrapXAxisLabels ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(31, "rotate-x-axis-labels", 
#nullable restore
#line (35,44)-(35,77) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
RotateXAxisLabels ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(32, "support-negative-data", 
#nullable restore
#line (36,45)-(36,80) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
SupportNegativeData ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(33, "rounded-ticks", 
#nullable restore
#line (37,37)-(37,65) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
RoundedTicks ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(34, "culture", 
#nullable restore
#line (38,30)-(38,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
Culture?.Name

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(35, "tick-values", 
#nullable restore
#line (39,34)-(39,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
TickValuesJson

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(36, "tick-format", 
#nullable restore
#line (40,34)-(40,44) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
TickFormat

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(37, "hide-tick-overlap", 
#nullable restore
#line (41,41)-(41,72) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
HideTickOverlap ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(38, "stroke-width", 
#nullable restore
#line (42,35)-(42,46) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
StrokeWidth

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(39, "show-x-axis-labels-tooltip", 
#nullable restore
#line (43,50)-(43,88) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
ShowXAxisLabelsTooltip ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(40, "date-localize-options", 
#nullable restore
#line (44,44)-(44,67) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
DateLocalizeOptionsJson

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(41, "mode", 
#nullable restore
#line (45,27)-(45,50) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
Mode.ToAttributeValue()

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(42, "secondary-y-axis-title", 
#nullable restore
#line (46,45)-(46,64) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
SecondaryYAxisTitle

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(43, "secondary-y-axis-tick-label-max-width", 
#nullable restore
#line (47,60)-(47,91) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
SecondaryYAxisTickLabelMaxWidth

#line default
#line hidden
#nullable disable
            );
            __builder.AddMultipleAttributes(44, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (48,34)-(48,54) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
            __builder.CloseElement();
#nullable restore
#line (52,2)-(54,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
if (CartesianTooltipTemplate is not null)
{

#line default
#line hidden
#nullable disable

            __builder.OpenElement(45, "div");
            __builder.AddAttribute(46, "id", 
#nullable restore
#line (54,15)-(54,31) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
_tooltipPortalId

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(47, "style", "display:none;position:absolute;");
#nullable restore
#line (54,74)-(54,140) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
__builder.AddContent(48, CartesianTooltipTemplate((CartesianTooltipContext)_tooltipContext)

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
#nullable restore
#line (55,1)-(58,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
}
else if (TooltipTemplate is not null)
{

#line default
#line hidden
#nullable disable

            __builder.OpenElement(49, "div");
            __builder.AddAttribute(50, "id", 
#nullable restore
#line (58,15)-(58,31) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
_tooltipPortalId

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(51, "style", "display:none;position:absolute;");
#nullable restore
#line (58,74)-(58,106) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
__builder.AddContent(52, TooltipTemplate(_tooltipContext)

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
#nullable restore
#line (59,1)-(60,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Charts/Charts/AreaChart/FluentAreaChart.razor"
}

#line default
#line hidden
#nullable disable

        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
