#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "0783669661515537a88372d1bdb7622f89bae66c3d129d721a1614f9dd3eb751"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
using Microsoft.FluentUI.AspNetCore.Components.Extensions

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentPresenceBadge : 
#nullable restore
#line (3,11)-(3,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
FluentComponentBase

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.Utilities.AddTag>(0);
            __builder.AddComponentParameter(1, nameof(global::Microsoft.FluentUI.AspNetCore.Components.Utilities.AddTag.
#nullable restore
#line (5,9)-(5,13) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
Name

#line default
#line hidden
#nullable disable
            ), "fluent-badge-container");
            __builder.AddComponentParameter(2, nameof(global::Microsoft.FluentUI.AspNetCore.Components.Utilities.AddTag.
#nullable restore
#line (5,39)-(5,46) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
TagWhen

#line default
#line hidden
#nullable disable
            ), (global::System.Func<global::System.Boolean>)(
#nullable restore
#line (5,50)-(5,67) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
() => _isAttached

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(3, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
#nullable restore
#line (6,1)-(6,2) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
	

#line default
#line hidden
#nullable disable

#nullable restore
#line (6,3)-(8,3) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
if (AnchorContent is not null)
	{
		

#line default
#line hidden
#nullable disable

#nullable restore
#line (8,145)-(9,3) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"

		

#line default
#line hidden
#nullable disable

#nullable restore
#line (9,4)-(9,17) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
__builder2.AddContent(4, AnchorContent

#line default
#line hidden
#nullable disable
                );
#nullable restore
#line (9,17)-(11,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"

	}

#line default
#line hidden
#nullable disable

                __builder2.OpenElement(5, "fluent-badge");
                __builder2.AddAttribute(6, "id", 
#nullable restore
#line (11,21)-(11,23) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
Id

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(7, "class", 
#nullable restore
#line (12,15)-(12,25) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
ClassValue

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(8, "style", 
#nullable restore
#line (13,15)-(13,25) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
StyleValue

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(9, "size", 
#nullable restore
#line (14,14)-(14,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
Size.ToAttributeValue()

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(10, "positioning", 
#nullable restore
#line (15,21)-(15,51) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
Positioning.ToAttributeValue()

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(11, "aria-label", 
#nullable restore
#line (16,20)-(16,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
_ariaLabel

#line default
#line hidden
#nullable disable
                );
                __builder2.AddMultipleAttributes(12, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (17,21)-(17,41) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
                ));
#nullable restore
#line (18,1)-(18,3) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
		

#line default
#line hidden
#nullable disable

#nullable restore
#line (18,4)-(20,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
if (Icon != null)
		{

#line default
#line hidden
#nullable disable

                global::__Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentPresenceBadge.TypeInference.CreateFluentIcon_0(__builder2, 13, 14, 
#nullable restore
#line (20,25)-(20,42) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
$"{_iconWidth}px"

#line default
#line hidden
#nullable disable
                , 15, 
#nullable restore
#line (20,53)-(20,57) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
Icon

#line default
#line hidden
#nullable disable
                , 16, 
#nullable restore
#line (20,66)-(20,82) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
FluentSlot.Start

#line default
#line hidden
#nullable disable
                , 17, 
#nullable restore
#line (20,91)-(20,114) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
Components.Color.Custom

#line default
#line hidden
#nullable disable
                , 18, 
#nullable restore
#line (20,130)-(20,144) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
GetIconColor()

#line default
#line hidden
#nullable disable
                , 19, "margin: -1px;");
#nullable restore
#line (21,1)-(22,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
		}

#line default
#line hidden
#nullable disable

                __builder2.CloseElement();
            }
            ));
            __builder.CloseComponent();
        }
        #pragma warning restore 1998
    }
}
namespace __Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentPresenceBadge
{
    #line hidden
    internal static class TypeInference
    {
        public static void CreateFluentIcon_0<Icon>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, global::System.String __arg0, int __seq1, Icon __arg1, int __seq2, global::System.String __arg2, int __seq3, global::Microsoft.FluentUI.AspNetCore.Components.Color? __arg3, int __seq4, global::System.String __arg4, int __seq5, global::System.String __arg5)
            where Icon : global::Microsoft.FluentUI.AspNetCore.Components.Icon, new()
        {
        __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (20,16)-(20,21) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
Width

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (20,45)-(20,50) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (20,59)-(20,63) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
Slot

#line default
#line hidden
#nullable disable
        ), __arg2);
        __builder.AddComponentParameter(__seq3, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (20,84)-(20,89) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
Color

#line default
#line hidden
#nullable disable
        ), __arg3);
        __builder.AddComponentParameter(__seq4, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (20,116)-(20,127) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
CustomColor

#line default
#line hidden
#nullable disable
        ), __arg4);
        __builder.AddComponentParameter(__seq5, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (20,146)-(20,151) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Badge/FluentPresenceBadge.razor"
Style

#line default
#line hidden
#nullable disable
        ), __arg5);
        __builder.CloseComponent();
        }
    }
}
#pragma warning restore 1591
