#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordion.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "3cd2f66b3645ae9955baa4636dcc6eef294dea51a5ddfd084e1b1db647e1eb7b"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordion.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordion.razor"
using Microsoft.FluentUI.AspNetCore.Components.Extensions

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentAccordion : 
#nullable restore
#line (3,11)-(3,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordion.razor"
FluentComponentBase

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            global::__Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentAccordion.TypeInference.CreateCascadingValue_0(__builder, 0, 1, 
#nullable restore
#line (4,24)-(4,28) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordion.razor"
this

#line default
#line hidden
#nullable disable
            , 2, 
#nullable restore
#line (4,39)-(4,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordion.razor"
true

#line default
#line hidden
#nullable disable
            , 3, (__builder2) => {
                __builder2.OpenElement(4, "fluent-accordion");
                __builder2.AddAttribute(5, "id", 
#nullable restore
#line (5,28)-(5,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordion.razor"
Id

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(6, "class", 
#nullable restore
#line (6,31)-(6,41) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordion.razor"
ClassValue

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(7, "style", 
#nullable restore
#line (7,31)-(7,41) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordion.razor"
StyleValue

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(8, "expand-mode", 
#nullable restore
#line (8,37)-(8,66) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordion.razor"
ExpandMode.ToAttributeValue()

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(9, "onaccordionchange", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.FluentUI.AspNetCore.Components.AccordionItemEventArgs>(this, 
#nullable restore
#line (9,43)-(9,72) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordion.razor"
HandleOnAccordionChangedAsync

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddMultipleAttributes(10, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (10,36)-(10,56) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordion.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
                ));
#nullable restore
#line (11,10)-(11,22) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordion.razor"
__builder2.AddContent(11, ChildContent

#line default
#line hidden
#nullable disable
                );
                __builder2.CloseElement();
            }
            );
        }
        #pragma warning restore 1998
    }
}
namespace __Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentAccordion
{
    #line hidden
    internal static class TypeInference
    {
        public static void CreateCascadingValue_0<TValue>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, TValue __arg0, int __seq1, global::System.Boolean __arg1, int __seq2, global::Microsoft.AspNetCore.Components.RenderFragment __arg2)
        {
        __builder.OpenComponent<global::Microsoft.AspNetCore.Components.CascadingValue<TValue>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::Microsoft.AspNetCore.Components.CascadingValue<TValue>.
#nullable restore
#line (4,17)-(4,22) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordion.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::Microsoft.AspNetCore.Components.CascadingValue<TValue>.
#nullable restore
#line (4,30)-(4,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordion.razor"
IsFixed

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, "ChildContent", __arg2);
        __builder.CloseComponent();
        }
    }
}
#pragma warning restore 1591
