#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "a14777e09d21350b886431f9b9fe241ae1012c6a325e4c85fa01274082b9fe10"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,50) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
using Microsoft.AspNetCore.Components.Rendering;

#nullable disable
#nullable restore
#line (3,2)-(3,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
using Microsoft.FluentUI.AspNetCore.Components.Extensions

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentErrorBoundary : 
#nullable restore
#line (4,11)-(4,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
FluentComponentBase

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            global::__Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentErrorBoundary.TypeInference.CreateCascadingValue_0(__builder, 0, 1, 
#nullable restore
#line (6,24)-(6,28) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
this

#line default
#line hidden
#nullable disable
            , 2, true, 3, (__builder2) => {
                __builder2.OpenComponent<global::Microsoft.AspNetCore.Components.Web.ErrorBoundary>(4);
                __builder2.AddComponentParameter(5, nameof(global::Microsoft.AspNetCore.Components.Web.ErrorBoundary.
#nullable restore
#line (7,41)-(7,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
MaximumErrorCount

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Int32>(
#nullable restore
#line (7,61)-(7,78) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
MaximumErrorCount

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(6, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    __builder3.OpenElement(7, "div");
                    __builder3.AddAttribute(8, "id", 
#nullable restore
#line (9,23)-(9,25) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
Id

#line default
#line hidden
#nullable disable
                    );
                    __builder3.AddAttribute(9, "class", 
#nullable restore
#line (9,35)-(9,62) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
DefaultClassBuilder.Build()

#line default
#line hidden
#nullable disable
                    );
                    __builder3.AddAttribute(10, "style", 
#nullable restore
#line (9,72)-(9,99) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
DefaultStyleBuilder.Build()

#line default
#line hidden
#nullable disable
                    );
                    __builder3.AddMultipleAttributes(11, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (9,115)-(9,135) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
                    ));
#nullable restore
#line (10,18)-(10,30) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
__builder3.AddContent(12, ChildContent

#line default
#line hidden
#nullable disable
                    );
                    __builder3.CloseElement();
                }
                ));
                __builder2.AddAttribute(13, "ErrorContent", (global::Microsoft.AspNetCore.Components.RenderFragment<global::System.Exception>)((context) => (__builder3) => {
#nullable restore
#line (14,1)-(14,13) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
            

#line default
#line hidden
#nullable disable

#nullable restore
#line (14,14)-(16,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
if (!HideChildContentOnError)
            {

#line default
#line hidden
#nullable disable

                    __builder3.OpenElement(14, "div");
                    __builder3.AddAttribute(15, "error");
                    __builder3.AddAttribute(16, "id", 
#nullable restore
#line (16,33)-(16,35) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
Id

#line default
#line hidden
#nullable disable
                    );
                    __builder3.AddAttribute(17, "class", 
#nullable restore
#line (16,45)-(16,72) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
DefaultClassBuilder.Build()

#line default
#line hidden
#nullable disable
                    );
                    __builder3.AddAttribute(18, "style", 
#nullable restore
#line (16,82)-(16,109) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
DefaultStyleBuilder.Build()

#line default
#line hidden
#nullable disable
                    );
                    __builder3.AddMultipleAttributes(19, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (16,125)-(16,145) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
                    ));
#nullable restore
#line (17,22)-(17,34) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
__builder3.AddContent(20, ChildContent

#line default
#line hidden
#nullable disable
                    );
                    __builder3.CloseElement();
#nullable restore
#line (19,1)-(20,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
            }

#line default
#line hidden
#nullable disable

                    __builder3.OpenElement(21, "fluent-dialog");
                    __builder3.AddAttribute(22, "type", "alert");
                    __builder3.AddAttribute(23, "ondialogtoggle", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.FluentUI.AspNetCore.Components.DialogToggleEventArgs>(this, 
#nullable restore
#line (21,59)-(21,72) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
OnToggleAsync

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.OpenElement(24, "fluent-dialog-body");
                    __builder3.OpenElement(25, "div");
                    __builder3.AddAttribute(26, "slot", "title");
                    __builder3.AddAttribute(27, "style", "display: flex; column-gap: 4px; align-items: center;");
#nullable restore
#line (24,1)-(24,25) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
                        

#line default
#line hidden
#nullable disable

#nullable restore
#line (24,26)-(26,29) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
if (ErrorHeader is null)
                        {
                            

#line default
#line hidden
#nullable disable

#nullable restore
#line (26,30)-(26,50) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
__builder3.AddContent(28, TitleIcon.ToMarkup()

#line default
#line hidden
#nullable disable
                    );
#nullable restore
#line (26,50)-(26,51) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
 

#line default
#line hidden
#nullable disable

#nullable restore
#line (26,52)-(26,84) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
__builder3.AddContent(29, Localizer["ErrorBoundary_Title"]

#line default
#line hidden
#nullable disable
                    );
#nullable restore
#line (26,84)-(30,29) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"

                        }
                        else
                        {
                            

#line default
#line hidden
#nullable disable

#nullable restore
#line (30,30)-(30,41) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
__builder3.AddContent(30, ErrorHeader

#line default
#line hidden
#nullable disable
                    );
#nullable restore
#line (30,41)-(32,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"

                        }

#line default
#line hidden
#nullable disable

                    __builder3.CloseElement();
                    __builder3.AddMarkupContent(31, "\n                    ");
                    __builder3.OpenElement(32, "div");
#nullable restore
#line (34,1)-(34,25) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
                        

#line default
#line hidden
#nullable disable

#nullable restore
#line (34,26)-(39,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
if (ErrorContent is null)
                        {
                            switch (DisplayErrorDetails)
                            {
                                case ErrorBoundaryDetails.ErrorMessage:
                                    

#line default
#line hidden
#nullable disable

#nullable restore
#line (39,38)-(39,53) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
__builder3.AddContent(33, context.Message

#line default
#line hidden
#nullable disable
                    );
#nullable restore
#line (39,53)-(43,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"

                                    break;

                                case ErrorBoundaryDetails.ErrorStack:

#line default
#line hidden
#nullable disable

                    __builder3.OpenElement(34, "div");
                    __builder3.AddAttribute(35, "style", "font-weight: bold;");
#nullable restore
#line (43,70)-(43,85) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
__builder3.AddContent(36, context.Message

#line default
#line hidden
#nullable disable
                    );
                    __builder3.AddContent(37, " (");
#nullable restore
#line (43,88)-(43,102) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
__builder3.AddContent(38, context.Source

#line default
#line hidden
#nullable disable
                    );
                    __builder3.AddContent(39, ")");
                    __builder3.CloseElement();
                    __builder3.AddMarkupContent(40, "\n                                    ");
                    __builder3.OpenElement(41, "pre");
                    __builder3.AddAttribute(42, "style", "overflow: auto; max-width: min(550px, calc(100vw - 50px)); max-height: 210px;");
#nullable restore
#line (44,130)-(44,148) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
__builder3.AddContent(43, context.StackTrace

#line default
#line hidden
#nullable disable
                    );
                    __builder3.CloseElement();
#nullable restore
#line (45,1)-(50,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
                            
                                    break;

                                case ErrorBoundaryDetails.None:
                                default:
                                    

#line default
#line hidden
#nullable disable

#nullable restore
#line (50,38)-(50,72) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
__builder3.AddContent(44, Localizer["ErrorBoundary_Message"]

#line default
#line hidden
#nullable disable
                    );
#nullable restore
#line (50,72)-(56,29) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"

                                    break;
                            }
                        }
                        else
                        {
                            

#line default
#line hidden
#nullable disable

#nullable restore
#line (56,30)-(56,42) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
__builder3.AddContent(45, ErrorContent

#line default
#line hidden
#nullable disable
                    );
#nullable restore
#line (56,42)-(58,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"

                        }

#line default
#line hidden
#nullable disable

                    __builder3.CloseElement();
                    __builder3.AddMarkupContent(46, "\n                    ");
                    __builder3.OpenElement(47, "fluent-button");
                    __builder3.AddAttribute(48, "slot", "action");
                    __builder3.AddAttribute(49, "appearance", "primary");
                    __builder3.AddAttribute(50, "onclick", 
#nullable restore
#line (59,81)-(59,103) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
GetOnclickJavaScript()

#line default
#line hidden
#nullable disable
                    );
#nullable restore
#line (60,26)-(60,58) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
__builder3.AddContent(51, Localizer["ErrorBoundary_Close"]

#line default
#line hidden
#nullable disable
                    );
                    __builder3.CloseElement();
                    __builder3.CloseElement();
                    __builder3.CloseElement();
                    __builder3.AddMarkupContent(52, "\n            ");
                    __builder3.AddMarkupContent(53, "<script>document.currentScript.previousElementSibling.show();</script>");
                }
                ));
                __builder2.AddComponentReferenceCapture(54, (__value) => {
#nullable restore
#line (7,26)-(7,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
ErrorBoundary

#line default
#line hidden
#nullable disable
                     = (global::Microsoft.AspNetCore.Components.Web.ErrorBoundary)__value;
                }
                );
                __builder2.CloseComponent();
            }
            );
        }
        #pragma warning restore 1998
    }
}
namespace __Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentErrorBoundary
{
    #line hidden
    internal static class TypeInference
    {
        public static void CreateCascadingValue_0<TValue>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, TValue __arg0, int __seq1, global::System.Boolean __arg1, int __seq2, global::Microsoft.AspNetCore.Components.RenderFragment __arg2)
        {
        __builder.OpenComponent<global::Microsoft.AspNetCore.Components.CascadingValue<TValue>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::Microsoft.AspNetCore.Components.CascadingValue<TValue>.
#nullable restore
#line (6,17)-(6,22) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::Microsoft.AspNetCore.Components.CascadingValue<TValue>.
#nullable restore
#line (6,30)-(6,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor"
IsFixed

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, "ChildContent", __arg2);
        __builder.CloseComponent();
        }
    }
}
#pragma warning restore 1591
