#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "2b6af66f3676825ad1667e1fa504a7224625f330bf352f1b5700b43de4f7057c"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentIcon<
#nullable restore
#line (2,12)-(2,16) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
Icon

#line default
#line hidden
#nullable disable
    > : 
#nullable restore
#line (3,11)-(3,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
FluentComponentBase

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
#nullable restore
#line (5,2)-(7,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
if (_icon.Size != IconSize.Custom && _icon.ContainsSVG)
{

#line default
#line hidden
#nullable disable

            __builder.OpenElement(0, "svg");
            __builder.AddAttribute(1, "id", 
#nullable restore
#line (7,15)-(7,17) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
Id

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(2, "slot", 
#nullable restore
#line (7,26)-(7,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
Slot

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(3, "class", 
#nullable restore
#line (9,18)-(9,28) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
ClassValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(4, "style", 
#nullable restore
#line (10,18)-(10,28) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
StyleValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(5, "focusable", 
#nullable restore
#line (11,23)-(11,51) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
Focusable ? "true" : "false"

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(6, "tabindex", 
#nullable restore
#line (12,21)-(12,113) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
AdditionalAttributes.GetValueIfNoAdditionalAttribute("tabindex", "0", when: () => Focusable)

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(7, "role", 
#nullable restore
#line (13,17)-(13,110) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
AdditionalAttributes.GetValueIfNoAdditionalAttribute("role", "button", when: () => Focusable)

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(8, "viewBox", 
#nullable restore
#line (14,21)-(14,67) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
$"0 0 {((int)_icon.Size)} {((int)_icon.Size)}"

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(9, "aria-hidden", 
#nullable restore
#line (15,25)-(15,50) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
Focusable ? null : "true"

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(10, "onkeydown", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.KeyboardEventArgs>(this, 
#nullable restore
#line (16,23)-(16,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
OnKeyDownAsync

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(11, "onclick", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (17,21)-(17,40) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
OnClickHandlerAsync

#line default
#line hidden
#nullable disable
            ));
            __builder.AddEventStopPropagationAttribute(12, "onclick", 
#nullable restore
#line (18,37)-(18,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
OnClickStopPropagation

#line default
#line hidden
#nullable disable
            );
            __builder.AddEventPreventDefaultAttribute(13, "onclick", 
#nullable restore
#line (19,36)-(19,57) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
OnClickPreventDefault

#line default
#line hidden
#nullable disable
            );
            __builder.AddMultipleAttributes(14, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (20,24)-(20,44) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
            __builder.AddElementReferenceCapture(15, (__value) => {
#nullable restore
#line (8,17)-(8,24) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
Element

#line default
#line hidden
#nullable disable
                 = __value;
            }
            );
#nullable restore
#line (21,1)-(21,9) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
        

#line default
#line hidden
#nullable disable

#nullable restore
#line (21,10)-(23,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
if (!string.IsNullOrEmpty(Title))
        {

#line default
#line hidden
#nullable disable

            __builder.OpenElement(16, "title");
#nullable restore
#line (23,21)-(23,26) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
__builder.AddContent(17, Title

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
#nullable restore
#line (24,1)-(25,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
        }

#line default
#line hidden
#nullable disable

#nullable restore
#line (25,11)-(25,39) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
__builder.AddContent(18, (MarkupString)@_icon.Content

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
#nullable restore
#line (27,1)-(30,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
}
else
{

#line default
#line hidden
#nullable disable

            __builder.OpenElement(19, "div");
            __builder.AddAttribute(20, "id", 
#nullable restore
#line (30,15)-(30,17) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
Id

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(21, "slot", 
#nullable restore
#line (32,17)-(32,21) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
Slot

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(22, "class", 
#nullable restore
#line (33,18)-(33,28) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
ClassValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(23, "style", 
#nullable restore
#line (34,18)-(34,28) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
StyleValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(24, "title", 
#nullable restore
#line (35,18)-(35,23) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
Title

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(25, "tabindex", 
#nullable restore
#line (36,21)-(36,113) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
AdditionalAttributes.GetValueIfNoAdditionalAttribute("tabindex", "0", when: () => Focusable)

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(26, "role", 
#nullable restore
#line (37,17)-(37,110) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
AdditionalAttributes.GetValueIfNoAdditionalAttribute("role", "button", when: () => Focusable)

#line default
#line hidden
#nullable disable
            );
            __builder.AddMultipleAttributes(27, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (38,24)-(38,44) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(28, "onkeydown", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.KeyboardEventArgs>(this, 
#nullable restore
#line (39,23)-(39,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
OnKeyDownAsync

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(29, "onclick", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (40,21)-(40,40) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
OnClickHandlerAsync

#line default
#line hidden
#nullable disable
            ));
            __builder.AddEventStopPropagationAttribute(30, "onclick", 
#nullable restore
#line (41,37)-(41,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
OnClickStopPropagation

#line default
#line hidden
#nullable disable
            );
            __builder.AddEventPreventDefaultAttribute(31, "onclick", 
#nullable restore
#line (42,36)-(42,57) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
OnClickPreventDefault

#line default
#line hidden
#nullable disable
            );
            __builder.AddElementReferenceCapture(32, (__value) => {
#nullable restore
#line (31,17)-(31,24) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
Element

#line default
#line hidden
#nullable disable
                 = __value;
            }
            );
#nullable restore
#line (43,11)-(43,39) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
__builder.AddContent(33, (MarkupString)@_icon.Content

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
#nullable restore
#line (45,1)-(46,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Icons/FluentIcon.razor"
}

#line default
#line hidden
#nullable disable

        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
