#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "8b20b54ddfe3362e7820e5d8ee72798b16bf630edbeff25ebced7f48ce4f4f3d"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor"
using Microsoft.FluentUI.AspNetCore.Components.Extensions

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentAccordionItem : 
#nullable restore
#line (3,11)-(3,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor"
FluentComponentBase

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "fluent-accordion-item");
            __builder.AddAttribute(1, "id", 
#nullable restore
#line (4,29)-(4,31) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor"
Id

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(2, "class", 
#nullable restore
#line (5,32)-(5,42) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor"
ClassValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(3, "style", 
#nullable restore
#line (6,32)-(6,42) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor"
StyleValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(4, "heading-level", 
#nullable restore
#line (7,39)-(7,51) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor"
HeadingLevel

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(5, "expanded", 
#nullable restore
#line (8,35)-(8,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor"
Expanded

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(6, "disabled", 
#nullable restore
#line (9,35)-(9,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor"
Disabled

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(7, "size", 
#nullable restore
#line (10,31)-(10,54) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor"
Size.ToAttributeValue()

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(8, "marker-position", 
#nullable restore
#line (11,42)-(11,75) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor"
MarkerPosition.ToAttributeValue()

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(9, "block", 
#nullable restore
#line (12,32)-(12,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor"
Block

#line default
#line hidden
#nullable disable
            );
            __builder.AddMultipleAttributes(10, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (13,37)-(13,57) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
#nullable restore
#line (14,1)-(14,5) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor"
    

#line default
#line hidden
#nullable disable

#nullable restore
#line (14,6)-(16,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor"
if (Header is not null || HeaderTemplate is not null)
    {

#line default
#line hidden
#nullable disable

            __builder.OpenElement(11, "span");
            __builder.AddAttribute(12, "slot", "heading");
#nullable restore
#line (17,14)-(17,20) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor"
__builder.AddContent(13, Header

#line default
#line hidden
#nullable disable
            );
            __builder.AddMarkupContent(14, "\n            ");
#nullable restore
#line (18,14)-(18,28) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor"
__builder.AddContent(15, HeaderTemplate

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
#nullable restore
#line (20,1)-(21,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor"
    }

#line default
#line hidden
#nullable disable

#nullable restore
#line (21,6)-(21,18) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Accordion/FluentAccordionItem.razor"
__builder.AddContent(16, ChildContent

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
