#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "316be45277b257ea0e1f2af8900cfda26b9d94874c4d7eac466444ee71411319"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
using Microsoft.FluentUI.AspNetCore.Components.Extensions

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentLink : 
#nullable restore
#line (3,11)-(3,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
FluentComponentBase

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "fluent-link");
            __builder.AddAttribute(1, "href", 
#nullable restore
#line (5,21)-(5,25) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
Href

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(2, "hreflang", 
#nullable restore
#line (6,16)-(6,24) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
HrefLang

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(3, "referrerpolicy", 
#nullable restore
#line (7,22)-(7,55) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
ReferrerPolicy.ToAttributeValue()

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(4, "rel", 
#nullable restore
#line (8,11)-(8,33) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
Rel.ToAttributeValue()

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(5, "type", 
#nullable restore
#line (9,12)-(9,20) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
LinkType

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(6, "target", 
#nullable restore
#line (10,14)-(10,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
Target.ToAttributeValue()

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(7, "appearance", 
#nullable restore
#line (11,18)-(11,70) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
Appearance.ToAttributeValue(returnEmptyAsNull: true)

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(8, "inline", 
#nullable restore
#line (12,14)-(12,20) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
Inline

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(9, "id", 
#nullable restore
#line (13,10)-(13,12) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
Id

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(10, "class", 
#nullable restore
#line (14,13)-(14,23) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
ClassValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(11, "style", 
#nullable restore
#line (15,13)-(15,23) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
StyleValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(12, "clickable", 
#nullable restore
#line (16,26)-(16,45) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
OnClick.HasDelegate

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(13, "force-load", 
#nullable restore
#line (17,19)-(17,44) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
ForceLoad ? "true" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(14, "onclick", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (18,16)-(18,35) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
OnClickHandlerAsync

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMultipleAttributes(15, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (19,18)-(19,38) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
#nullable restore
#line (20,1)-(20,2) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
	

#line default
#line hidden
#nullable disable

#nullable restore
#line (20,3)-(22,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
if (IconStart is not null)
	{

#line default
#line hidden
#nullable disable

            global::__Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentLink.TypeInference.CreateFluentIcon_0(__builder, 16, 17, 
#nullable restore
#line (22,23)-(22,32) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
IconStart

#line default
#line hidden
#nullable disable
            , 18, "16", 19, "me-1");
#nullable restore
#line (23,1)-(24,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
	}

#line default
#line hidden
#nullable disable

#nullable restore
#line (24,3)-(24,15) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
__builder.AddContent(20, ChildContent

#line default
#line hidden
#nullable disable
            );
#nullable restore
#line (25,1)-(25,2) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
	

#line default
#line hidden
#nullable disable

#nullable restore
#line (25,3)-(27,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
if (IconEnd is not null)
	{

#line default
#line hidden
#nullable disable

            global::__Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentLink.TypeInference.CreateFluentIcon_1(__builder, 21, 22, 
#nullable restore
#line (27,23)-(27,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
IconEnd

#line default
#line hidden
#nullable disable
            , 23, "16", 24, "ms-1");
#nullable restore
#line (28,1)-(29,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
	}

#line default
#line hidden
#nullable disable

            __builder.CloseElement();
        }
        #pragma warning restore 1998
    }
}
namespace __Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentLink
{
    #line hidden
    internal static class TypeInference
    {
        public static void CreateFluentIcon_0<Icon>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, Icon __arg0, int __seq1, global::System.String __arg1, int __seq2, global::System.String __arg2)
            where Icon : global::Microsoft.FluentUI.AspNetCore.Components.Icon, new()
        {
        __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (22,15)-(22,20) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (22,34)-(22,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
Width

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (22,45)-(22,51) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
Margin

#line default
#line hidden
#nullable disable
        ), __arg2);
        __builder.CloseComponent();
        }
        public static void CreateFluentIcon_1<Icon>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, Icon __arg0, int __seq1, global::System.String __arg1, int __seq2, global::System.String __arg2)
            where Icon : global::Microsoft.FluentUI.AspNetCore.Components.Icon, new()
        {
        __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (27,15)-(27,20) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (27,32)-(27,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
Width

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (27,43)-(27,49) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Link/FluentLink.razor"
Margin

#line default
#line hidden
#nullable disable
        ), __arg2);
        __builder.CloseComponent();
        }
    }
}
#pragma warning restore 1591
