#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "8212e71441f2d19b062a42c78c0865c4da3af956a6ca9703f34a14934b4ad9d2"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
using Microsoft.FluentUI.AspNetCore.Components.Extensions

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentLabelInfo : 
#nullable restore
#line (3,11)-(3,22) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
FluentLabel

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "span");
            __builder.AddAttribute(1, "id", 
#nullable restore
#line (5,12)-(5,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
Id

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(2, "class", 
#nullable restore
#line (6,15)-(6,25) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
ClassValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(3, "style", 
#nullable restore
#line (7,15)-(7,25) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
StyleValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddMultipleAttributes(4, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (8,20)-(8,40) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
#nullable restore
#line (10,1)-(10,5) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
    

#line default
#line hidden
#nullable disable

#nullable restore
#line (10,6)-(12,9) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
if (FluentField is null)
    {
        

#line default
#line hidden
#nullable disable

#nullable restore
#line (12,10)-(12,22) 24 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
__builder.AddContent(5, ChildContent

#line default
#line hidden
#nullable disable
            );
#nullable restore
#line (12,22)-(16,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"

    }
    else
    {

#line default
#line hidden
#nullable disable

            __builder.OpenElement(6, "fluent-label");
            __builder.AddAttribute(7, "size", 
#nullable restore
#line (16,30)-(16,53) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
Size.ToAttributeValue()

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(8, "weight", 
#nullable restore
#line (17,32)-(17,57) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
Weight.ToAttributeValue()

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(9, "disabled", 
#nullable restore
#line (18,34)-(18,42) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
Disabled

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(10, "required", 
#nullable restore
#line (19,34)-(19,42) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
Required

#line default
#line hidden
#nullable disable
            );
#nullable restore
#line (20,14)-(20,26) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
__builder.AddContent(11, ChildContent

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
#nullable restore
#line (22,1)-(23,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
    }

#line default
#line hidden
#nullable disable

#nullable restore
#line (24,1)-(24,5) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
    

#line default
#line hidden
#nullable disable

#nullable restore
#line (24,6)-(26,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
if (HasInfoContent)
    {

#line default
#line hidden
#nullable disable

            __builder.OpenElement(12, "button");
            __builder.AddAttribute(13, "id", 
#nullable restore
#line (26,22)-(26,35) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
_infoButtonId

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(14, "type", "button");
            __builder.AddAttribute(15, "aria-label", 
#nullable restore
#line (28,31)-(28,134) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
string.IsNullOrEmpty(InfoText) ? Localizer[Localization.LanguageResource.LabelInfo_InfoText] : InfoText

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(16, "aria-expanded", 
#nullable restore
#line (29,34)-(29,64) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
_infoOpened ? "true" : "false"

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(17, "onclick", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (30,27)-(30,44) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
OnInfoToggleAsync

#line default
#line hidden
#nullable disable
            ));
            global::__Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentLabelInfo.TypeInference.CreateFluentIcon_0(__builder, 18, 19, 
#nullable restore
#line (31,33)-(31,41) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
InfoIcon

#line default
#line hidden
#nullable disable
            , 20, "rest");
            __builder.AddMarkupContent(21, "\n            ");
            global::__Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentLabelInfo.TypeInference.CreateFluentIcon_1(__builder, 22, 23, 
#nullable restore
#line (33,33)-(33,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
InfoIconActive

#line default
#line hidden
#nullable disable
            , 24, "active");
            __builder.CloseElement();
#nullable restore
#line (36,1)-(37,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"


#line default
#line hidden
#nullable disable

            __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentPopover>(25);
            __builder.AddComponentParameter(26, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentPopover.
#nullable restore
#line (37,24)-(37,32) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
AnchorId

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (37,35)-(37,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
_infoButtonId

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(27, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentPopover.
#nullable restore
#line (38,24)-(38,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
Opened

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (38,33)-(38,44) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
_infoOpened

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(28, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentPopover.
#nullable restore
#line (39,24)-(39,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
OpenedChanged

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Boolean>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Boolean>(this, 
#nullable restore
#line (39,41)-(39,69) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
value => _infoOpened = value

#line default
#line hidden
#nullable disable
            )));
            __builder.AddAttribute(29, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
#nullable restore
#line (40,1)-(40,13) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
            

#line default
#line hidden
#nullable disable

#nullable restore
#line (40,14)-(42,17) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
if (InfoTemplate is not null)
            {
                

#line default
#line hidden
#nullable disable

#nullable restore
#line (42,18)-(42,30) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
__builder2.AddContent(30, InfoTemplate

#line default
#line hidden
#nullable disable
                );
#nullable restore
#line (42,30)-(46,17) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"

            }
            else
            {
                

#line default
#line hidden
#nullable disable

#nullable restore
#line (46,18)-(48,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
if (!string.IsNullOrEmpty(InfoText))
                {

#line default
#line hidden
#nullable disable

                __builder2.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentText>(31);
                __builder2.AddComponentParameter(32, "part", "info-text");
                __builder2.AddAttribute(33, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
#nullable restore
#line (49,26)-(49,34) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
__builder3.AddContent(34, InfoText

#line default
#line hidden
#nullable disable
                    );
                }
                ));
                __builder2.CloseComponent();
#nullable restore
#line (51,1)-(51,18) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
                }

#line default
#line hidden
#nullable disable

#nullable restore
#line (51,18)-(53,17) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"


                

#line default
#line hidden
#nullable disable

#nullable restore
#line (53,18)-(55,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
if (!string.IsNullOrEmpty(InfoActionLink))
                {

#line default
#line hidden
#nullable disable

                __builder2.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentLink>(35);
                __builder2.AddComponentParameter(36, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentLink.
#nullable restore
#line (55,33)-(55,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
Href

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (55,40)-(55,54) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
InfoActionLink

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(37, "part", "info-link");
                __builder2.AddComponentParameter(38, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentLink.
#nullable restore
#line (57,33)-(57,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
Target

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.LinkTarget?>(
#nullable restore
#line (57,42)-(57,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
InfoActionTarget

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(39, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
#nullable restore
#line (58,27)-(58,110) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
__builder3.AddContent(40, InfoActionText ?? Localizer[Localization.LanguageResource.LabelInfo_InfoActionText]

#line default
#line hidden
#nullable disable
                    );
                }
                ));
                __builder2.CloseComponent();
#nullable restore
#line (60,1)-(60,18) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
                }

#line default
#line hidden
#nullable disable

#nullable restore
#line (60,18)-(62,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"

            }

#line default
#line hidden
#nullable disable

            }
            ));
            __builder.CloseComponent();
#nullable restore
#line (63,1)-(64,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
    }

#line default
#line hidden
#nullable disable

            __builder.CloseElement();
        }
        #pragma warning restore 1998
    }
}
namespace __Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentLabelInfo
{
    #line hidden
    internal static class TypeInference
    {
        public static void CreateFluentIcon_0<Icon>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, Icon __arg0, int __seq1, global::System.Object __arg1)
            where Icon : global::Microsoft.FluentUI.AspNetCore.Components.Icon, new()
        {
        __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (31,25)-(31,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, "part", __arg1);
        __builder.CloseComponent();
        }
        public static void CreateFluentIcon_1<Icon>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, Icon __arg0, int __seq1, global::System.Object __arg1)
            where Icon : global::Microsoft.FluentUI.AspNetCore.Components.Icon, new()
        {
        __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (33,25)-(33,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Label/FluentLabelInfo.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, "part", __arg1);
        __builder.CloseComponent();
        }
    }
}
#pragma warning restore 1591
