#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "a6ebabb1864a4a917b8fd04f278baf86c3c9101a3d48f1a3d5490d01cd08a8f8"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
using Microsoft.FluentUI.AspNetCore.Components.Extensions

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentTextInput : 
#nullable restore
#line (3,11)-(3,44) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
FluentInputImmediateBase<string?>

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentField>(0);
            __builder.AddComponentParameter(1, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentField.
#nullable restore
#line (5,14)-(5,28) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
InputComponent

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.IFluentField>(
#nullable restore
#line (5,31)-(5,35) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
this

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(2, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentField.
#nullable restore
#line (5,37)-(5,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
ValueExpression

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.LambdaExpression>(
#nullable restore
#line (5,55)-(5,73) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
ValidationFieldFor

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(3, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentField.
#nullable restore
#line (5,75)-(5,80) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
ForId

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (5,83)-(5,85) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
Id

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(4, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentField.
#nullable restore
#line (5,87)-(5,92) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
Class

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (5,95)-(5,105) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
ClassValue

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(5, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentField.
#nullable restore
#line (5,107)-(5,112) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
Style

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (5,115)-(5,125) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
StyleValue

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(6, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentField.
#nullable restore
#line (5,127)-(5,131) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
Size

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.FieldSize?>(
#nullable restore
#line (5,134)-(5,152) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
Size.ToFieldSize()

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(7, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.OpenElement(8, "fluent-text-input");
                __builder2.AddAttribute(9, "style", 
#nullable restore
#line (7,32)-(7,51) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
ComponentStyleValue

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(10, "appearance", 
#nullable restore
#line (8,37)-(8,66) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
Appearance.ToAttributeValue()

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(11, "autocomplete", 
#nullable restore
#line (9,39)-(9,51) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
AutoComplete

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(12, "autofocus", 
#nullable restore
#line (10,36)-(10,45) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
Autofocus

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(13, "aria-label", 
#nullable restore
#line (11,37)-(11,46) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
AriaLabel

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(14, "disabled", 
#nullable restore
#line (12,35)-(12,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
Disabled

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(15, "id", 
#nullable restore
#line (13,29)-(13,31) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
Id

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(16, "inputmode", 
#nullable restore
#line (14,36)-(14,64) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
InputMode.ToAttributeValue()

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(17, "list", 
#nullable restore
#line (15,30)-(15,38) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
DataList

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(18, "maxlength", 
#nullable restore
#line (16,36)-(16,45) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
MaxLength

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(19, "minlength", 
#nullable restore
#line (17,36)-(17,45) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
MinLength

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(20, "name", 
#nullable restore
#line (18,31)-(18,35) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
Name

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(21, "pattern", 
#nullable restore
#line (19,34)-(19,41) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
Pattern

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(22, "placeholder", 
#nullable restore
#line (20,38)-(20,49) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
Placeholder

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(23, "readonly", 
#nullable restore
#line (21,35)-(21,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
ReadOnly

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(24, "required", 
#nullable restore
#line (22,35)-(22,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
Required

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(25, "slot", 
#nullable restore
#line (23,31)-(23,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
FluentSlot.FieldInput

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(26, "spellcheck", 
#nullable restore
#line (24,37)-(24,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
Spellcheck

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(27, "control-size", 
#nullable restore
#line (25,39)-(25,62) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
Size.ToAttributeValue()

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(28, "type", 
#nullable restore
#line (26,31)-(26,63) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
TextInputType.ToAttributeValue()

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(29, "value", 
#nullable restore
#line (27,32)-(27,54) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
ImmediateValueAsString

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(30, "onfocusin", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.FocusEventArgs>(this, 
#nullable restore
#line (28,37)-(28,56) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
FocusInHandlerAsync

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(31, "onfocusout", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.FocusEventArgs>(this, 
#nullable restore
#line (29,38)-(29,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
FocusOutHandlerAsync

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(32, "onchange", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.ChangeEventArgs>(this, 
#nullable restore
#line (30,36)-(30,54) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
ChangeHandlerAsync

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(33, "ontextimmediate", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.ChangeEventArgs>(this, 
#nullable restore
#line (31,43)-(31,60) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
InputHandlerAsync

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddMultipleAttributes(34, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (32,37)-(32,57) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddElementReferenceCapture(35, (__value) => {
#nullable restore
#line (6,31)-(6,38) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
Element

#line default
#line hidden
#nullable disable
                     = __value;
                }
                );
#nullable restore
#line (34,1)-(34,9) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
        

#line default
#line hidden
#nullable disable

#nullable restore
#line (34,10)-(36,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
if (StartTemplate != null)
        {

#line default
#line hidden
#nullable disable

                __builder2.OpenElement(36, "div");
                __builder2.AddAttribute(37, "slot", 
#nullable restore
#line (36,25)-(36,41) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
FluentSlot.Start

#line default
#line hidden
#nullable disable
                );
#nullable restore
#line (37,18)-(37,31) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
__builder2.AddContent(38, StartTemplate

#line default
#line hidden
#nullable disable
                );
                __builder2.CloseElement();
#nullable restore
#line (39,1)-(40,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
        }

#line default
#line hidden
#nullable disable

#nullable restore
#line (41,1)-(41,9) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
        

#line default
#line hidden
#nullable disable

#nullable restore
#line (41,10)-(43,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
if (EndTemplate != null)
        {

#line default
#line hidden
#nullable disable

                __builder2.OpenElement(39, "div");
                __builder2.AddAttribute(40, "slot", 
#nullable restore
#line (43,25)-(43,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
FluentSlot.End

#line default
#line hidden
#nullable disable
                );
#nullable restore
#line (44,18)-(44,29) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
__builder2.AddContent(41, EndTemplate

#line default
#line hidden
#nullable disable
                );
                __builder2.CloseElement();
#nullable restore
#line (46,1)-(47,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextInput/FluentTextInput.razor"
        }

#line default
#line hidden
#nullable disable

                __builder2.CloseElement();
            }
            ));
            __builder.CloseComponent();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
