#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "4227a031cf0599ca187d787424232edbd7ba3175d9d2dcc7b535a8fe00ab0951"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor"
using Microsoft.FluentUI.AspNetCore.Components.Extensions

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentProgressBar : 
#nullable restore
#line (3,11)-(3,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor"
FluentComponentBase

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
#nullable restore
#line (5,2)-(7,5) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor"
if (Visible.HasValue)
{
    

#line default
#line hidden
#nullable disable

#nullable restore
#line (7,6)-(9,9) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor"
if (HasCustomStyle)
    {
        

#line default
#line hidden
#nullable disable

#nullable restore
#line (9,10)-(9,23) 24 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor"
__builder.AddContent(0, CustomStyle()

#line default
#line hidden
#nullable disable
            );
#nullable restore
#line (9,23)-(10,6) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor"

    }

#line default
#line hidden
#nullable disable

#nullable restore
#line (10,6)-(11,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor"


#line default
#line hidden
#nullable disable

            __builder.OpenElement(1, "fluent-progress-bar");
            __builder.AddAttribute(2, "id", 
#nullable restore
#line (11,31)-(11,38) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor"
GetId()

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(3, "class", 
#nullable restore
#line (12,34)-(12,44) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor"
ClassValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(4, "style", 
#nullable restore
#line (13,34)-(13,44) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor"
StyleValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(5, "min", 
#nullable restore
#line (14,32)-(14,35) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor"
Min

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(6, "max", 
#nullable restore
#line (15,32)-(15,35) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor"
Max

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(7, "shape", 
#nullable restore
#line (16,34)-(16,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor"
Shape.ToAttributeValue()

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(8, "thickness", 
#nullable restore
#line (17,38)-(17,61) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor"
GetThicknessAttribute()

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(9, "value", 
#nullable restore
#line (18,34)-(18,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor"
Value

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(10, "validation-state", 
#nullable restore
#line (19,45)-(19,69) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor"
State.ToAttributeValue()

#line default
#line hidden
#nullable disable
            );
            __builder.AddMultipleAttributes(11, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (20,39)-(20,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
            __builder.CloseElement();
#nullable restore
#line (21,1)-(22,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Progress/FluentProgressBar.razor"
}

#line default
#line hidden
#nullable disable

        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
