#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "a4cb9ab512707b2f3ca54e3a6a544e70c1240f0ac50e3603e981165c854a7267"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
using Microsoft.FluentUI.AspNetCore.Components.Extensions

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentTreeItem : 
#nullable restore
#line (3,11)-(3,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
FluentComponentBase

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "fluent-tree-item");
            __builder.AddAttribute(1, "id", 
#nullable restore
#line (5,24)-(5,26) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
Id

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(2, "class", 
#nullable restore
#line (6,27)-(6,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
ClassValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(3, "style", 
#nullable restore
#line (7,27)-(7,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
StyleValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(4, "appearance", 
#nullable restore
#line (8,32)-(8,90) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
Appearance.ToAttributeValue(isNull: TreeAppearance.Subtle)

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(5, "size", 
#nullable restore
#line (9,26)-(9,72) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
Size.ToAttributeValue(isNull: TreeSize.Medium)

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(6, "selected", 
#nullable restore
#line (10,30)-(10,40) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
IsSelected

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(7, "expanded", 
#nullable restore
#line (11,30)-(11,38) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
Expanded

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(8, "ontreechanged", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.FluentUI.AspNetCore.Components.TreeItemChangedEventArgs>(this, 
#nullable restore
#line (12,36)-(12,54) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
OnTreeChangedAsync

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(9, "ontreetoggle", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.FluentUI.AspNetCore.Components.TreeItemToggleEventArgs>(this, 
#nullable restore
#line (13,35)-(13,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
OnTreeToggleAsync

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMultipleAttributes(10, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (14,32)-(14,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
#nullable restore
#line (17,1)-(17,5) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
    

#line default
#line hidden
#nullable disable

#nullable restore
#line (17,6)-(19,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
if (IconCollapsed is not null || IconExpanded is not null)
    {

#line default
#line hidden
#nullable disable

            __builder.OpenElement(11, "span");
            __builder.AddAttribute(12, "slot", 
#nullable restore
#line (19,22)-(19,40) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
FluentSlot.Chevron

#line default
#line hidden
#nullable disable
            );
#nullable restore
#line (20,1)-(20,13) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
            

#line default
#line hidden
#nullable disable

#nullable restore
#line (20,14)-(22,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
if (IconCollapsed is not null)
            {

#line default
#line hidden
#nullable disable

            global::__Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentTreeItem.TypeInference.CreateFluentIcon_0(__builder, 13, 14, true, 15, 
#nullable restore
#line (22,47)-(22,60) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
IconCollapsed

#line default
#line hidden
#nullable disable
            , 16, 
#nullable restore
#line (22,69)-(22,81) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
Color.Custom

#line default
#line hidden
#nullable disable
            , 17, "currentColor");
#nullable restore
#line (23,1)-(23,17) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
                

#line default
#line hidden
#nullable disable

#nullable restore
#line (23,19)-(23,69) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
__builder.AddContent(18, IconExpanded is null ? DefaultIcon_Expanded : null

#line default
#line hidden
#nullable disable
            );
#nullable restore
#line (23,70)-(25,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"

            }

#line default
#line hidden
#nullable disable

#nullable restore
#line (26,1)-(26,13) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
            

#line default
#line hidden
#nullable disable

#nullable restore
#line (26,14)-(28,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
if (IconExpanded is not null)
            {

#line default
#line hidden
#nullable disable

            global::__Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentTreeItem.TypeInference.CreateFluentIcon_1(__builder, 19, 20, true, 21, 
#nullable restore
#line (28,46)-(28,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
IconExpanded

#line default
#line hidden
#nullable disable
            , 22, 
#nullable restore
#line (28,67)-(28,79) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
Color.Custom

#line default
#line hidden
#nullable disable
            , 23, "currentColor");
#nullable restore
#line (29,1)-(29,17) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
                

#line default
#line hidden
#nullable disable

#nullable restore
#line (29,19)-(29,71) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
__builder.AddContent(24, IconCollapsed is null ? DefaultIcon_Collapsed : null

#line default
#line hidden
#nullable disable
            );
#nullable restore
#line (29,72)-(31,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"

            }

#line default
#line hidden
#nullable disable

            __builder.CloseElement();
#nullable restore
#line (32,1)-(34,5) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
    }

    

#line default
#line hidden
#nullable disable

#nullable restore
#line (34,15)-(35,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"


#line default
#line hidden
#nullable disable

#nullable restore
#line (35,1)-(35,5) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
    

#line default
#line hidden
#nullable disable

#nullable restore
#line (35,6)-(37,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
if (!string.IsNullOrEmpty(Text))
    {

#line default
#line hidden
#nullable disable

            __builder.OpenElement(25, "span");
            __builder.AddAttribute(26, "part", "text");
#nullable restore
#line (38,14)-(38,18) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
__builder.AddContent(27, Text

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
#nullable restore
#line (40,1)-(42,5) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
    }

    

#line default
#line hidden
#nullable disable

#nullable restore
#line (42,39)-(43,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"


#line default
#line hidden
#nullable disable

#nullable restore
#line (43,6)-(43,18) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
__builder.AddContent(28, ChildContent

#line default
#line hidden
#nullable disable
            );
#nullable restore
#line (46,1)-(46,5) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
    

#line default
#line hidden
#nullable disable

#nullable restore
#line (46,6)-(50,13) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
if (OwnerTreeView is not null && Items is not null)
    {
        if (OwnerTreeView.LazyLoadItems && Items.Any() && !Expanded)
        {
            

#line default
#line hidden
#nullable disable

#nullable restore
#line (50,78)-(51,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"


#line default
#line hidden
#nullable disable

            __builder.OpenElement(29, "fluent-tree-item");
#nullable restore
#line (51,32)-(51,96) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
__builder.AddContent(30, Localizer[Localization.LanguageResource.TreeItem_LoadingMessage]

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
#nullable restore
#line (52,1)-(57,17) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
        }
        else
        {
            foreach (var item in Items)
            {
                

#line default
#line hidden
#nullable disable

#nullable restore
#line (57,18)-(57,71) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
__builder.AddContent(31, FluentTreeItem.GetFluentTreeItem(OwnerTreeView, item)

#line default
#line hidden
#nullable disable
            );
#nullable restore
#line (57,71)-(62,5) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"

            }
        }
    }

    

#line default
#line hidden
#nullable disable

#nullable restore
#line (62,16)-(63,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"


#line default
#line hidden
#nullable disable

#nullable restore
#line (63,1)-(63,5) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
    

#line default
#line hidden
#nullable disable

#nullable restore
#line (63,6)-(65,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
if (IconStart is not null)
    {

#line default
#line hidden
#nullable disable

            __builder.OpenElement(32, "span");
            __builder.AddAttribute(33, "slot", 
#nullable restore
#line (65,22)-(65,38) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
FluentSlot.Start

#line default
#line hidden
#nullable disable
            );
            global::__Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentTreeItem.TypeInference.CreateFluentIcon_2(__builder, 34, 35, 
#nullable restore
#line (66,33)-(66,42) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
IconStart

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
#nullable restore
#line (68,1)-(70,5) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
    }

    

#line default
#line hidden
#nullable disable

#nullable restore
#line (70,14)-(71,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"


#line default
#line hidden
#nullable disable

#nullable restore
#line (71,1)-(71,5) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
    

#line default
#line hidden
#nullable disable

#nullable restore
#line (71,6)-(73,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
if (IconEnd is not null)
    {

#line default
#line hidden
#nullable disable

            __builder.OpenElement(36, "span");
            __builder.AddAttribute(37, "slot", 
#nullable restore
#line (73,22)-(73,36) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
FluentSlot.End

#line default
#line hidden
#nullable disable
            );
            global::__Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentTreeItem.TypeInference.CreateFluentIcon_3(__builder, 38, 39, 
#nullable restore
#line (74,33)-(74,40) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
IconEnd

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
#nullable restore
#line (76,1)-(78,5) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
    }

    

#line default
#line hidden
#nullable disable

#nullable restore
#line (78,16)-(79,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"


#line default
#line hidden
#nullable disable

#nullable restore
#line (79,1)-(79,5) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
    

#line default
#line hidden
#nullable disable

#nullable restore
#line (79,6)-(81,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
if (IconAside is not null)
    {

#line default
#line hidden
#nullable disable

            __builder.OpenElement(40, "span");
            __builder.AddAttribute(41, "slot", 
#nullable restore
#line (81,22)-(81,38) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
FluentSlot.Aside

#line default
#line hidden
#nullable disable
            );
            global::__Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentTreeItem.TypeInference.CreateFluentIcon_4(__builder, 42, 43, 
#nullable restore
#line (82,33)-(82,42) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
IconAside

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
#nullable restore
#line (84,1)-(85,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
    }

#line default
#line hidden
#nullable disable

            __builder.CloseElement();
        }
        #pragma warning restore 1998
    }
}
namespace __Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentTreeItem
{
    #line hidden
    internal static class TypeInference
    {
        public static void CreateFluentIcon_0<Icon>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, global::System.Object __arg0, int __seq1, Icon __arg1, int __seq2, global::Microsoft.FluentUI.AspNetCore.Components.Color? __arg2, int __seq3, global::System.String __arg3)
            where Icon : global::Microsoft.FluentUI.AspNetCore.Components.Icon, new()
        {
        __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>>(seq);
        __builder.AddComponentParameter(__seq0, "collapsed", __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (22,39)-(22,44) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (22,62)-(22,67) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
Color

#line default
#line hidden
#nullable disable
        ), __arg2);
        __builder.AddComponentParameter(__seq3, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (22,83)-(22,94) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
CustomColor

#line default
#line hidden
#nullable disable
        ), __arg3);
        __builder.CloseComponent();
        }
        public static void CreateFluentIcon_1<Icon>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, global::System.Object __arg0, int __seq1, Icon __arg1, int __seq2, global::Microsoft.FluentUI.AspNetCore.Components.Color? __arg2, int __seq3, global::System.String __arg3)
            where Icon : global::Microsoft.FluentUI.AspNetCore.Components.Icon, new()
        {
        __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>>(seq);
        __builder.AddComponentParameter(__seq0, "expanded", __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (28,38)-(28,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (28,60)-(28,65) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
Color

#line default
#line hidden
#nullable disable
        ), __arg2);
        __builder.AddComponentParameter(__seq3, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (28,81)-(28,92) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
CustomColor

#line default
#line hidden
#nullable disable
        ), __arg3);
        __builder.CloseComponent();
        }
        public static void CreateFluentIcon_2<Icon>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, Icon __arg0)
            where Icon : global::Microsoft.FluentUI.AspNetCore.Components.Icon, new()
        {
        __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (66,25)-(66,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.CloseComponent();
        }
        public static void CreateFluentIcon_3<Icon>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, Icon __arg0)
            where Icon : global::Microsoft.FluentUI.AspNetCore.Components.Icon, new()
        {
        __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (74,25)-(74,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.CloseComponent();
        }
        public static void CreateFluentIcon_4<Icon>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, Icon __arg0)
            where Icon : global::Microsoft.FluentUI.AspNetCore.Components.Icon, new()
        {
        __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (82,25)-(82,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TreeView/FluentTreeItem.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.CloseComponent();
        }
    }
}
#pragma warning restore 1591
