#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "93bdd41ca700034b24e4fdee110bd762586eb843182005c8b14e43aee1185899"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentEmoji<
#nullable restore
#line (2,12)-(2,17) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
Emoji

#line default
#line hidden
#nullable disable
    > : 
#nullable restore
#line (3,11)-(3,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
FluentComponentBase

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
#nullable restore
#line (5,2)-(7,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
if (ContainsSVG())
{

#line default
#line hidden
#nullable disable

            __builder.OpenElement(0, "svg");
            __builder.AddAttribute(1, "id", 
#nullable restore
#line (7,15)-(7,17) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
Id

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(2, "slot", 
#nullable restore
#line (7,26)-(7,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
Slot

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(3, "class", 
#nullable restore
#line (7,40)-(7,50) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
ClassValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(4, "style", 
#nullable restore
#line (7,60)-(7,70) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
StyleValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(5, "focusable", "false");
            __builder.AddAttribute(6, "viewBox", 
#nullable restore
#line (7,101)-(7,149) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
$"0 0 {((int)_emoji.Size)} {((int)_emoji.Size)}"

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(7, "aria-hidden", "true");
            __builder.AddAttribute(8, "onclick", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (7,182)-(7,201) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
OnClickHandlerAsync

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMultipleAttributes(9, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (7,217)-(7,237) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
#nullable restore
#line (8,1)-(8,9) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
        

#line default
#line hidden
#nullable disable

#nullable restore
#line (8,10)-(10,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
if (!string.IsNullOrEmpty(Title))
        {

#line default
#line hidden
#nullable disable

            __builder.OpenElement(10, "title");
#nullable restore
#line (10,21)-(10,26) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
__builder.AddContent(11, Title

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
#nullable restore
#line (11,1)-(12,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
        }

#line default
#line hidden
#nullable disable

#nullable restore
#line (12,11)-(12,40) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
__builder.AddContent(12, (MarkupString)@_emoji.Content

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
#nullable restore
#line (14,1)-(17,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
}
else
{

#line default
#line hidden
#nullable disable

            __builder.OpenElement(13, "div");
            __builder.AddAttribute(14, "id", 
#nullable restore
#line (17,15)-(17,17) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
Id

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(15, "slot", 
#nullable restore
#line (17,26)-(17,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
Slot

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(16, "class", 
#nullable restore
#line (17,40)-(17,50) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
ClassValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(17, "style", 
#nullable restore
#line (17,60)-(17,70) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
StyleValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(18, "title", 
#nullable restore
#line (17,80)-(17,85) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
Title

#line default
#line hidden
#nullable disable
            );
            __builder.AddMultipleAttributes(19, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (17,101)-(17,121) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(20, "onclick", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (17,134)-(17,153) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
OnClickHandlerAsync

#line default
#line hidden
#nullable disable
            ));
#nullable restore
#line (17,157)-(17,186) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
__builder.AddContent(21, (MarkupString)@_emoji.Content

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
#nullable restore
#line (18,1)-(18,2) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Emojis/FluentEmoji.razor"
}

#line default
#line hidden
#nullable disable

        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
