#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "6eb9d0bb5c0cf371df449cd5887c96ad8c9101f6e1abbcfca97b89cc35c80a75"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentDatePicker<
#nullable restore
#line (3,12)-(3,18) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
TValue

#line default
#line hidden
#nullable disable
    > : 
#nullable restore
#line (2,11)-(2,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
FluentCalendarBase<TValue>

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput>(0);
            __builder.AddComponentParameter(1, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (5,18)-(5,20) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Id

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (5,23)-(5,25) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Id

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(2, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (7,18)-(7,36) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
ValidationFieldFor

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.LambdaExpression>(
#nullable restore
#line (7,39)-(7,54) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
ValueExpression

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(3, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (8,18)-(8,23) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Class

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (8,26)-(8,36) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
ClassValue

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(4, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (9,18)-(9,23) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Style

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (9,26)-(9,36) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
StyleValue

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(5, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (10,18)-(10,23) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Label

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (10,26)-(10,31) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Label

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(6, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (11,18)-(11,31) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
LabelTemplate

#line default
#line hidden
#nullable disable
            ), (global::Microsoft.AspNetCore.Components.RenderFragment)(
#nullable restore
#line (11,34)-(11,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
LabelTemplate

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(7, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (12,18)-(12,31) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
LabelPosition

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.LabelPosition?>(
#nullable restore
#line (12,34)-(12,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
LabelPosition

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(8, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (13,18)-(13,28) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
LabelWidth

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (13,31)-(13,41) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
LabelWidth

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(9, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (14,18)-(14,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
AriaLabel

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (14,30)-(14,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
AriaLabel

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(10, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (15,18)-(15,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
AutoComplete

#line default
#line hidden
#nullable disable
            ), "off");
            __builder.AddComponentParameter(11, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (16,18)-(16,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Autofocus

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (16,30)-(16,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Autofocus

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(12, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (17,18)-(17,28) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Appearance

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.TextInputAppearance>(
#nullable restore
#line (17,31)-(17,41) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Appearance

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(13, "onclick", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (19,29)-(19,50) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
OnTextInputClickAsync

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(14, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (20,18)-(20,26) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
ReadOnly

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (20,29)-(20,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
ReadOnly

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(15, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (21,18)-(21,26) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Disabled

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean?>(
#nullable restore
#line (21,29)-(21,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Disabled

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(16, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (22,18)-(22,26) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Required

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean?>(
#nullable restore
#line (22,29)-(22,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Required

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(17, "type", 
#nullable restore
#line (23,25)-(23,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
GetInputType()

#line default
#line hidden
#nullable disable
            );
            __builder.AddComponentParameter(18, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (24,18)-(24,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
InputMode

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.TextInputMode?>(
#nullable restore
#line (24,30)-(24,44) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
GetInputMode()

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(19, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (25,18)-(25,25) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Message

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (25,28)-(25,35) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Message

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(20, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (26,18)-(26,29) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
MessageIcon

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.Icon>(
#nullable restore
#line (26,32)-(26,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
MessageIcon

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(21, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (27,18)-(27,34) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
MessageCondition

#line default
#line hidden
#nullable disable
            ), (global::System.Func<global::Microsoft.FluentUI.AspNetCore.Components.IFluentField, global::System.Boolean>)(
#nullable restore
#line (27,37)-(27,53) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
MessageCondition

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(22, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (28,18)-(28,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
MessageState

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.MessageState?>(
#nullable restore
#line (28,33)-(28,45) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
MessageState

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(23, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (29,18)-(29,33) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
MessageTemplate

#line default
#line hidden
#nullable disable
            ), (global::Microsoft.AspNetCore.Components.RenderFragment)(
#nullable restore
#line (29,36)-(29,51) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
MessageTemplate

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(24, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (30,18)-(30,29) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Placeholder

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (30,32)-(30,63) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
GetPlaceholderAccordingToView()

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(25, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (31,18)-(31,23) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Width

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (31,26)-(31,31) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Width

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(26, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (32,18)-(32,22) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Name

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (32,25)-(32,29) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Name

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMultipleAttributes(27, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (33,32)-(33,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(28, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (18,24)-(18,29) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (18,32)-(18,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
CurrentValueAsString

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(29, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.String>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.String>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => CurrentValueAsString = __value, CurrentValueAsString))));
            __builder.AddComponentParameter(30, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.String>>>(() => CurrentValueAsString));
            __builder.AddAttribute(31, "EndTemplate", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
#nullable restore
#line (35,1)-(35,9) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
        

#line default
#line hidden
#nullable disable

#nullable restore
#line (35,10)-(37,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
if (IsFluentUIStyle)
        {

#line default
#line hidden
#nullable disable

                global::__Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentDatePicker.TypeInference.CreateFluentIcon_0(__builder2, 32, 33, 
#nullable restore
#line (38,33)-(38,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Icon

#line default
#line hidden
#nullable disable
                , 34, 
#nullable restore
#line (39,36)-(39,40) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
true

#line default
#line hidden
#nullable disable
                , 35, global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.KeyboardEventArgs>(this, 
#nullable restore
#line (40,38)-(40,56) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
OnIconKeydownAsync

#line default
#line hidden
#nullable disable
                ), 36, 
#nullable restore
#line (41,38)-(41,101) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Localizer[Localization.LanguageResource.DatePicker_ButtonTitle]

#line default
#line hidden
#nullable disable
                , 37, 
#nullable restore
#line (42,33)-(42,96) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Localizer[Localization.LanguageResource.DatePicker_ButtonTitle]

#line default
#line hidden
#nullable disable
                , 38, (__value) => {
#nullable restore
#line (37,31)-(37,36) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
_icon

#line default
#line hidden
#nullable disable
                     = __value;
                }
                );
#nullable restore
#line (43,1)-(44,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
        }

#line default
#line hidden
#nullable disable

            }
            ));
            __builder.AddComponentReferenceCapture(39, (__value) => {
#nullable restore
#line (6,24)-(6,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
_input

#line default
#line hidden
#nullable disable
                 = (global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput)__value;
            }
            );
            __builder.CloseComponent();
#nullable restore
#line (47,2)-(49,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
if (IsFluentUIStyle)
{

#line default
#line hidden
#nullable disable

            __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentPopover>(40);
            __builder.AddComponentParameter(41, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentPopover.
#nullable restore
#line (49,20)-(49,28) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
AnchorId

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (49,31)-(49,33) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Id

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(42, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentPopover.
#nullable restore
#line (49,41)-(49,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Opened

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (49,50)-(49,56) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Opened

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(43, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentPopover.OpenedChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Boolean>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Boolean>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Opened = __value, Opened))));
            __builder.AddAttribute(44, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentCalendar<
#nullable restore
#line (51,33)-(51,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
TValue

#line default
#line hidden
#nullable disable
                >>(45);
                __builder2.AddComponentParameter(46, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCalendar<TValue>.
#nullable restore
#line (52,25)-(52,32) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Culture

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Globalization.CultureInfo>(
#nullable restore
#line (52,35)-(52,42) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Culture

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(47, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCalendar<TValue>.
#nullable restore
#line (53,25)-(53,29) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
View

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.CalendarViews>(
#nullable restore
#line (53,32)-(53,36) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
View

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(48, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCalendar<TValue>.
#nullable restore
#line (54,25)-(54,32) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
MinDate

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<TValue>(
#nullable restore
#line (54,35)-(54,42) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
MinDate

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(49, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCalendar<TValue>.
#nullable restore
#line (55,25)-(55,32) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
MaxDate

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<TValue>(
#nullable restore
#line (55,35)-(55,42) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
MaxDate

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(50, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCalendar<TValue>.
#nullable restore
#line (56,25)-(56,34) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
DayFormat

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.CalendarDayFormat?>(
#nullable restore
#line (56,37)-(56,46) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
DayFormat

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(51, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCalendar<TValue>.
#nullable restore
#line (57,25)-(57,41) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
DisabledDateFunc

#line default
#line hidden
#nullable disable
                ), (global::System.Func<TValue, global::System.Boolean>)(
#nullable restore
#line (57,44)-(57,60) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
DisabledDateFunc

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(52, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCalendar<TValue>.
#nullable restore
#line (58,25)-(58,56) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
DisabledCheckAllDaysOfMonthYear

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (58,59)-(58,90) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
DisabledCheckAllDaysOfMonthYear

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(53, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCalendar<TValue>.
#nullable restore
#line (59,25)-(59,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
DisabledSelectable

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (59,46)-(59,64) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
DisabledSelectable

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(54, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCalendar<TValue>.
#nullable restore
#line (60,25)-(60,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Value

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<TValue>(
#nullable restore
#line (60,33)-(60,38) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Value

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(55, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCalendar<TValue>.
#nullable restore
#line (61,25)-(61,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
ValueChanged

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<TValue>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<TValue>(this, 
#nullable restore
#line (61,40)-(61,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
OnSelectedDateAsync

#line default
#line hidden
#nullable disable
                )));
                __builder2.AddComponentParameter(56, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCalendar<TValue>.
#nullable restore
#line (62,25)-(62,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
DaysTemplate

#line default
#line hidden
#nullable disable
                ), (global::Microsoft.AspNetCore.Components.RenderFragment<global::Microsoft.FluentUI.AspNetCore.Components.FluentCalendarDay<TValue>>)(
#nullable restore
#line (62,40)-(62,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
DaysTemplate

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(57, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCalendar<TValue>.
#nullable restore
#line (63,25)-(63,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
PickerMonthChanged

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<TValue>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<TValue>(this, 
#nullable restore
#line (63,46)-(63,76) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
PickerMonthChangedHandlerAsync

#line default
#line hidden
#nullable disable
                )));
                __builder2.AddComponentReferenceCapture(58, (__value) => {
#nullable restore
#line (50,31)-(50,40) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
_calendar

#line default
#line hidden
#nullable disable
                     = (global::Microsoft.FluentUI.AspNetCore.Components.FluentCalendar<TValue>)__value;
                }
                );
                __builder2.CloseComponent();
            }
            ));
            __builder.CloseComponent();
#nullable restore
#line (65,1)-(66,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
}

#line default
#line hidden
#nullable disable

        }
        #pragma warning restore 1998
    }
}
namespace __Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentDatePicker
{
    #line hidden
    internal static class TypeInference
    {
        public static void CreateFluentIcon_0<Icon>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, Icon __arg0, int __seq1, global::System.Boolean __arg1, int __seq2, global::System.Object __arg2, int __seq3, global::System.Object __arg3, int __seq4, global::System.String __arg4, int __seq5, global::System.Action<global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>> __arg5)
            where Icon : global::Microsoft.FluentUI.AspNetCore.Components.Icon, new()
        {
        __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (38,25)-(38,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (39,25)-(39,34) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Focusable

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, "onkeydown", __arg2);
        __builder.AddComponentParameter(__seq3, "aria-label", __arg3);
        __builder.AddComponentParameter(__seq4, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (42,25)-(42,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentDatePicker.razor"
Title

#line default
#line hidden
#nullable disable
        ), __arg4);
        __builder.AddComponentReferenceCapture(__seq5, (__value) => { __arg5((global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>)__value); });
        __builder.CloseComponent();
        }
    }
}
#pragma warning restore 1591
