#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "856cbf3a6c6fc02350bb6591e48b414eaf2093a09873efda49d0af9ef2a99004"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentSkeleton : 
#nullable restore
#line (2,11)-(2,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
FluentComponentBase

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
#nullable restore
#line (4,2)-(6,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
if (Visible)
{

#line default
#line hidden
#nullable disable

            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "id", 
#nullable restore
#line (6,15)-(6,17) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
Id

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(2, "class", 
#nullable restore
#line (7,18)-(7,28) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
ClassValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(3, "style", 
#nullable restore
#line (8,18)-(8,28) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
StyleValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(4, "shape", 
#nullable restore
#line (9,19)-(9,45) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
Circular ? "circle" : null

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(5, "shimmer", 
#nullable restore
#line (10,20)-(10,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
Shimmer

#line default
#line hidden
#nullable disable
            );
            __builder.AddMultipleAttributes(6, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (11,24)-(11,44) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
#nullable restore
#line (14,10)-(14,36) 24 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
__builder.AddContent(7, ChildContent?.Invoke(this)

#line default
#line hidden
#nullable disable
            );
#nullable restore
#line (17,1)-(17,9) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
        

#line default
#line hidden
#nullable disable

#nullable restore
#line (17,10)-(20,17) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
switch (Pattern)
        {
             case SkeletonPattern.Icon:
                

#line default
#line hidden
#nullable disable

#nullable restore
#line (20,18)-(20,36) 24 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
__builder.AddContent(8, DrawCircle("48px")

#line default
#line hidden
#nullable disable
            );
#nullable restore
#line (20,36)-(25,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"


                break;

            case SkeletonPattern.IconTitle:

#line default
#line hidden
#nullable disable

            __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentStack>(9);
            __builder.AddAttribute(10, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
#nullable restore
#line (26,22)-(26,40) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
__builder2.AddContent(11, DrawCircle("48px")

#line default
#line hidden
#nullable disable
                );
                __builder2.AddMarkupContent(12, "\n                    ");
#nullable restore
#line (27,22)-(27,51) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
__builder2.AddContent(13, DrawRectangle("100%", "48px")

#line default
#line hidden
#nullable disable
                );
            }
            ));
            __builder.CloseComponent();
#nullable restore
#line (29,1)-(33,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"

                break;

            case SkeletonPattern.IconTitleContent:

#line default
#line hidden
#nullable disable

            __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentStack>(14);
            __builder.AddAttribute(15, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
#nullable restore
#line (34,22)-(34,40) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
__builder2.AddContent(16, DrawCircle("48px")

#line default
#line hidden
#nullable disable
                );
                __builder2.AddMarkupContent(17, "\n                    ");
#nullable restore
#line (35,22)-(35,51) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
__builder2.AddContent(18, DrawRectangle("100%", "48px")

#line default
#line hidden
#nullable disable
                );
            }
            ));
            __builder.CloseComponent();
#nullable restore
#line (37,1)-(37,17) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
                

#line default
#line hidden
#nullable disable

#nullable restore
#line (37,18)-(37,47) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
__builder.AddContent(19, DrawRectangle("auto", "100%")

#line default
#line hidden
#nullable disable
            );
#nullable restore
#line (37,47)-(41,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"


                break;
        }

#line default
#line hidden
#nullable disable

            __builder.CloseElement();
#nullable restore
#line (42,1)-(43,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Skeleton/FluentSkeleton.razor"
}

#line default
#line hidden
#nullable disable

        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
