#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "3735372f3f22c61a20a060f16998e328ded24f679de1f4e760ad0cda29332d8b"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentTimePicker<
#nullable restore
#line (3,12)-(3,18) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
TValue

#line default
#line hidden
#nullable disable
    > : 
#nullable restore
#line (2,11)-(2,34) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
FluentInputBase<TValue>

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
#nullable restore
#line (5,2)-(7,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
if (IsFluentUIStyle)
{

#line default
#line hidden
#nullable disable

            __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<
#nullable restore
#line (9,30)-(9,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
DateTime?

#line default
#line hidden
#nullable disable
            , 
#nullable restore
#line (10,29)-(10,38) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
DateTime?

#line default
#line hidden
#nullable disable
            >>(0);
            __builder.AddComponentParameter(1, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (8,21)-(8,23) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Id

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (8,26)-(8,28) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Id

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(2, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (11,21)-(11,26) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Class

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (11,29)-(11,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
ClassValue

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(3, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (12,21)-(12,26) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Style

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (12,29)-(12,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
StyleValue

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(4, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (13,21)-(13,26) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Label

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (13,29)-(13,34) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Label

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(5, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (14,21)-(14,34) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
LabelTemplate

#line default
#line hidden
#nullable disable
            ), (global::Microsoft.AspNetCore.Components.RenderFragment)(
#nullable restore
#line (14,37)-(14,50) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
LabelTemplate

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(6, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (15,21)-(15,34) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
LabelPosition

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.LabelPosition?>(
#nullable restore
#line (15,37)-(15,50) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
LabelPosition

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(7, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (16,21)-(16,31) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
LabelWidth

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (16,34)-(16,44) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
LabelWidth

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(8, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (17,21)-(17,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
AriaLabel

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (17,33)-(17,42) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
AriaLabel

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(9, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (18,21)-(18,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Autofocus

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (18,33)-(18,42) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Autofocus

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(10, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (19,21)-(19,31) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Appearance

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.ListAppearance?>(
#nullable restore
#line (19,34)-(19,44) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Appearance

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(11, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (20,21)-(20,29) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
ReadOnly

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (20,32)-(20,40) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
ReadOnly

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(12, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (21,21)-(21,29) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Disabled

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean?>(
#nullable restore
#line (21,32)-(21,40) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Disabled

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(13, "onkeydown", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.KeyboardEventArgs>(this, 
#nullable restore
#line (23,34)-(23,53) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
KeyDownHandlerAsync

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(14, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (24,21)-(24,31) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
OptionText

#line default
#line hidden
#nullable disable
            ), (global::System.Func<DateTime?, global::System.String>)(
#nullable restore
#line (24,35)-(24,64) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
i => i?.ToString(TimePattern)

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(15, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (25,21)-(25,40) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
OptionValueToString

#line default
#line hidden
#nullable disable
            ), (global::System.Func<DateTime?, global::System.String>)(
#nullable restore
#line (25,44)-(25,71) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
i => FormatValueAsString(i)

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(16, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (26,21)-(26,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
OptionSelectedComparer

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEqualityComparer<DateTime?>>(
#nullable restore
#line (26,46)-(26,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
TimeComparer

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(17, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (27,21)-(27,35) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
OptionDisabled

#line default
#line hidden
#nullable disable
            ), (global::System.Func<DateTime?, global::System.Boolean>)(
#nullable restore
#line (27,38)-(27,56) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
DisableHourHandler

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(18, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (28,21)-(28,29) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Required

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean?>(
#nullable restore
#line (28,32)-(28,40) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Required

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(19, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (29,21)-(29,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Indicator

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.Icon>(
#nullable restore
#line (29,34)-(29,114) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
new CoreIcons.Regular.Size20.Clock().WithColor("var(--colorNeutralForeground3)")

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(20, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (30,21)-(30,26) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Items

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<DateTime?>>(
#nullable restore
#line (30,29)-(30,34) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Items

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(21, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (31,21)-(31,28) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Message

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (31,31)-(31,38) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Message

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(22, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (32,21)-(32,32) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
MessageIcon

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.Icon>(
#nullable restore
#line (32,35)-(32,46) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
MessageIcon

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(23, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (33,21)-(33,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
MessageCondition

#line default
#line hidden
#nullable disable
            ), (global::System.Func<global::Microsoft.FluentUI.AspNetCore.Components.IFluentField, global::System.Boolean>)(
#nullable restore
#line (33,40)-(33,56) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
MessageCondition

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(24, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (34,21)-(34,33) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
MessageState

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.MessageState?>(
#nullable restore
#line (34,36)-(34,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
MessageState

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(25, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (35,21)-(35,36) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
MessageTemplate

#line default
#line hidden
#nullable disable
            ), (global::Microsoft.AspNetCore.Components.RenderFragment)(
#nullable restore
#line (35,39)-(35,54) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
MessageTemplate

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(26, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (36,21)-(36,32) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Placeholder

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (36,35)-(36,66) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
GetPlaceholderAccordingToView()

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(27, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (37,21)-(37,26) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Width

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (37,29)-(37,34) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Width

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(28, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (38,21)-(38,25) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Name

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (38,28)-(38,32) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Name

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMultipleAttributes(29, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (39,35)-(39,55) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(30, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.
#nullable restore
#line (22,27)-(22,32) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<DateTime?>(
#nullable restore
#line (22,34)-(22,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
SelectedValue

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(31, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<DateTime?>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<DateTime?>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => SelectedValue = __value, SelectedValue))));
            __builder.AddComponentParameter(32, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<DateTime?>>>(() => SelectedValue));
            __builder.AddComponentReferenceCapture(33, (__value) => {
#nullable restore
#line (7,27)-(7,42) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
_fluentCombobox

#line default
#line hidden
#nullable disable
                 = (global::Microsoft.FluentUI.AspNetCore.Components.FluentCombobox<DateTime?, DateTime?>)__value;
            }
            );
            __builder.CloseComponent();
#nullable restore
#line (41,1)-(44,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
}
else
{

#line default
#line hidden
#nullable disable

            __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput>(34);
            __builder.AddComponentParameter(35, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (44,22)-(44,24) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Id

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (44,27)-(44,29) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Id

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(36, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (45,22)-(45,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Class

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (45,30)-(45,40) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
ClassValue

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(37, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (46,22)-(46,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Style

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (46,30)-(46,40) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
StyleValue

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(38, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (47,22)-(47,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Label

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (47,30)-(47,35) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Label

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(39, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (48,22)-(48,35) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
LabelTemplate

#line default
#line hidden
#nullable disable
            ), (global::Microsoft.AspNetCore.Components.RenderFragment)(
#nullable restore
#line (48,38)-(48,51) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
LabelTemplate

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(40, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (49,22)-(49,35) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
LabelPosition

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.LabelPosition?>(
#nullable restore
#line (49,38)-(49,51) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
LabelPosition

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(41, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (50,22)-(50,32) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
LabelWidth

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (50,35)-(50,45) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
LabelWidth

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(42, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (51,22)-(51,31) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
AriaLabel

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (51,34)-(51,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
AriaLabel

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(43, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (52,22)-(52,34) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
AutoComplete

#line default
#line hidden
#nullable disable
            ), "off");
            __builder.AddComponentParameter(44, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (53,22)-(53,31) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Autofocus

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (53,34)-(53,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Autofocus

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(45, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (54,22)-(54,32) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Appearance

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.TextInputAppearance>(
#nullable restore
#line (54,35)-(54,54) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
TextInputAppearance

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(46, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (56,22)-(56,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
ReadOnly

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (56,33)-(56,41) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
ReadOnly

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(47, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (57,22)-(57,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Disabled

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean?>(
#nullable restore
#line (57,33)-(57,41) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Disabled

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(48, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (58,22)-(58,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Required

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean?>(
#nullable restore
#line (58,33)-(58,41) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Required

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(49, "type", "time");
            __builder.AddComponentParameter(50, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (60,22)-(60,29) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Message

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (60,32)-(60,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Message

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(51, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (61,22)-(61,33) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
MessageIcon

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.Icon>(
#nullable restore
#line (61,36)-(61,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
MessageIcon

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(52, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (62,22)-(62,38) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
MessageCondition

#line default
#line hidden
#nullable disable
            ), (global::System.Func<global::Microsoft.FluentUI.AspNetCore.Components.IFluentField, global::System.Boolean>)(
#nullable restore
#line (62,41)-(62,57) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
MessageCondition

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(53, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (63,22)-(63,34) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
MessageState

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.MessageState?>(
#nullable restore
#line (63,37)-(63,49) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
MessageState

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(54, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (64,22)-(64,37) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
MessageTemplate

#line default
#line hidden
#nullable disable
            ), (global::Microsoft.AspNetCore.Components.RenderFragment)(
#nullable restore
#line (64,40)-(64,55) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
MessageTemplate

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(55, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (65,22)-(65,33) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Placeholder

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (65,36)-(65,67) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
GetPlaceholderAccordingToView()

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(56, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (66,22)-(66,26) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Name

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (66,29)-(66,33) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Name

#line default
#line hidden
#nullable disable
            ));
            __builder.AddMultipleAttributes(57, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (67,36)-(67,56) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(58, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.
#nullable restore
#line (55,28)-(55,33) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (55,36)-(55,56) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
CurrentValueAsString

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(59, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.String>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.String>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => CurrentValueAsString = __value, CurrentValueAsString))));
            __builder.AddComponentParameter(60, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentTextInput.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.String>>>(() => CurrentValueAsString));
            __builder.CloseComponent();
#nullable restore
#line (68,1)-(69,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/DateTime/FluentTimePicker.razor"
}

#line default
#line hidden
#nullable disable

        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
