#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "661799058411125139aa32a0e4d85ad22eef49461ff6a44aa995e3fb1c8bc08a"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
using Microsoft.FluentUI.AspNetCore.Components.Extensions

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentTextArea : 
#nullable restore
#line (3,11)-(3,44) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
FluentInputImmediateBase<string?>

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentField>(0);
            __builder.AddComponentParameter(1, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentField.
#nullable restore
#line (5,14)-(5,28) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
InputComponent

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.IFluentField>(
#nullable restore
#line (5,31)-(5,35) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
this

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(2, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentField.
#nullable restore
#line (5,37)-(5,42) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
ForId

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (5,45)-(5,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
Id

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(3, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentField.
#nullable restore
#line (5,49)-(5,54) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
Class

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (5,57)-(5,67) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
ClassValue

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(4, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentField.
#nullable restore
#line (5,69)-(5,74) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
Style

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (5,77)-(5,87) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
StyleValue

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(5, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentField.
#nullable restore
#line (5,89)-(5,93) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
Size

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.FluentUI.AspNetCore.Components.FieldSize?>(
#nullable restore
#line (5,96)-(5,114) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
Size.ToFieldSize()

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(6, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.OpenElement(7, "fluent-textarea");
                __builder2.AddAttribute(8, "style", 
#nullable restore
#line (7,30)-(7,49) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
ComponentStyleValue

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(9, "appearance", 
#nullable restore
#line (8,35)-(8,64) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
Appearance.ToAttributeValue()

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(10, "autocomplete", 
#nullable restore
#line (9,37)-(9,49) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
AutoComplete

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(11, "autofocus", 
#nullable restore
#line (10,34)-(10,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
Autofocus

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(12, "auto-resize", 
#nullable restore
#line (11,36)-(11,46) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
AutoResize

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(13, "aria-label", 
#nullable restore
#line (12,35)-(12,44) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
AriaLabel

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(14, "disabled", 
#nullable restore
#line (13,33)-(13,41) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
Disabled

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(15, "display-shadow", 
#nullable restore
#line (14,39)-(14,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
DisplayShadow

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(16, "id", 
#nullable restore
#line (15,27)-(15,29) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
Id

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(17, "maxlength", 
#nullable restore
#line (16,34)-(16,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
MaxLength

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(18, "minlength", 
#nullable restore
#line (17,34)-(17,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
MinLength

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(19, "name", 
#nullable restore
#line (18,29)-(18,33) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
Name

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(20, "placeholder", 
#nullable restore
#line (19,36)-(19,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
Placeholder

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(21, "readonly", 
#nullable restore
#line (20,33)-(20,41) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
ReadOnly

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(22, "required", 
#nullable restore
#line (21,33)-(21,41) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
Required

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(23, "size", 
#nullable restore
#line (22,29)-(22,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
Size.ToAttributeValue()

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(24, "slot", 
#nullable restore
#line (23,29)-(23,50) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
FluentSlot.FieldInput

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(25, "spellcheck", 
#nullable restore
#line (24,35)-(24,50) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
SpellCheckValue

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(26, "resize", 
#nullable restore
#line (25,31)-(25,56) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
Resize.ToAttributeValue()

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(27, "value", 
#nullable restore
#line (26,30)-(26,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
ImmediateValueAsString

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(28, "onfocusin", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.FocusEventArgs>(this, 
#nullable restore
#line (27,35)-(27,54) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
FocusInHandlerAsync

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(29, "onfocusout", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.FocusEventArgs>(this, 
#nullable restore
#line (28,36)-(28,56) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
FocusOutHandlerAsync

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(30, "onchange", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.ChangeEventArgs>(this, 
#nullable restore
#line (29,34)-(29,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
ChangeHandlerAsync

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(31, "ontextimmediate", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.ChangeEventArgs>(this, 
#nullable restore
#line (30,41)-(30,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
InputHandlerAsync

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddMultipleAttributes(32, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (31,35)-(31,55) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddElementReferenceCapture(33, (__value) => {
#nullable restore
#line (6,29)-(6,36) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/TextArea/FluentTextArea.razor"
Element

#line default
#line hidden
#nullable disable
                     = __value;
                }
                );
                __builder2.CloseElement();
            }
            ));
            __builder.CloseComponent();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
