#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "0795922b836e92730655e3bcf3a5bb0eb5eb24a9ef14b06fddf9f0086b48db2f"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
using Microsoft.FluentUI.AspNetCore.Components.Extensions

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentRatingDisplay : 
#nullable restore
#line (3,11)-(3,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
FluentComponentBase

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "fluent-rating-display");
            __builder.AddAttribute(1, "id", 
#nullable restore
#line (5,29)-(5,31) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
Id

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(2, "class", 
#nullable restore
#line (6,32)-(6,42) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
ClassValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(3, "style", 
#nullable restore
#line (7,32)-(7,42) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
StyleValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(4, "count", 
#nullable restore
#line (8,32)-(8,106) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
Count?.ToString("0.00", System.Globalization.CultureInfo.InvariantCulture)

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(5, "compact", 
#nullable restore
#line (9,34)-(9,41) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
Compact

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(6, "max", 
#nullable restore
#line (10,30)-(10,33) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
Max

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(7, "size", 
#nullable restore
#line (11,31)-(11,54) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
Size.ToAttributeValue()

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(8, "color", 
#nullable restore
#line (12,32)-(12,56) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
Color.ToAttributeValue()

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(9, "value", 
#nullable restore
#line (13,32)-(13,106) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
Value?.ToString("0.00", System.Globalization.CultureInfo.InvariantCulture)

#line default
#line hidden
#nullable disable
            );
            __builder.AddMultipleAttributes(10, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (14,37)-(14,57) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
#nullable restore
#line (16,1)-(16,5) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
    

#line default
#line hidden
#nullable disable

#nullable restore
#line (16,6)-(18,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
if (Shape is not null)
    {

#line default
#line hidden
#nullable disable

            global::__Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentRatingDisplay.TypeInference.CreateFluentIcon_0(__builder, 11, 12, 
#nullable restore
#line (18,29)-(18,34) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
Shape

#line default
#line hidden
#nullable disable
            , 13, 
#nullable restore
#line (18,43)-(18,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
FluentSlot.Icon

#line default
#line hidden
#nullable disable
            );
#nullable restore
#line (19,1)-(20,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
    }

#line default
#line hidden
#nullable disable

            __builder.CloseElement();
        }
        #pragma warning restore 1998
    }
}
namespace __Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentRatingDisplay
{
    #line hidden
    internal static class TypeInference
    {
        public static void CreateFluentIcon_0<Icon>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, Icon __arg0, int __seq1, global::System.String __arg1)
            where Icon : global::Microsoft.FluentUI.AspNetCore.Components.Icon, new()
        {
        __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (18,21)-(18,26) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (18,36)-(18,40) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/RatingDisplay/FluentRatingDisplay.razor"
Slot

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.CloseComponent();
        }
    }
}
#pragma warning restore 1591
