#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "5807eab43290a87f6ad86709f6bca6c09422b3a7dbfc76c7cc2c16e2172a8e95"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentOption<
#nullable restore
#line (3,12)-(3,18) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
TValue

#line default
#line hidden
#nullable disable
    > : 
#nullable restore
#line (2,11)-(2,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
FluentComponentBase

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "fluent-option");
            __builder.AddAttribute(1, "id", 
#nullable restore
#line (5,21)-(5,23) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
Id

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(2, "class", 
#nullable restore
#line (6,24)-(6,51) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
DefaultClassBuilder.Build()

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(3, "style", 
#nullable restore
#line (7,24)-(7,51) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
DefaultStyleBuilder.Build()

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(4, "disabled", 
#nullable restore
#line (8,27)-(8,35) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
Disabled

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(5, "name", 
#nullable restore
#line (9,23)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
Name

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(6, "text", 
#nullable restore
#line (10,23)-(10,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
Text

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(7, "value", 
#nullable restore
#line (11,24)-(11,38) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
ValueFormatted

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(8, "selected", 
#nullable restore
#line (12,27)-(12,35) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
Selected

#line default
#line hidden
#nullable disable
            );
            __builder.AddMultipleAttributes(9, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (13,30)-(13,50) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
#nullable restore
#line (14,6)-(14,18) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
__builder.AddContent(10, ChildContent

#line default
#line hidden
#nullable disable
            );
#nullable restore
#line (16,1)-(16,5) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
    

#line default
#line hidden
#nullable disable

#nullable restore
#line (16,6)-(18,9) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
if (ChildContent is null && !string.IsNullOrEmpty(Text))
    {
        

#line default
#line hidden
#nullable disable

#nullable restore
#line (18,10)-(18,14) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
__builder.AddContent(11, Text

#line default
#line hidden
#nullable disable
            );
#nullable restore
#line (18,14)-(20,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"

    }

#line default
#line hidden
#nullable disable

#nullable restore
#line (21,1)-(21,5) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
    

#line default
#line hidden
#nullable disable

#nullable restore
#line (21,6)-(23,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
if (!string.IsNullOrWhiteSpace(Description))
    {

#line default
#line hidden
#nullable disable

            __builder.OpenElement(12, "span");
            __builder.AddAttribute(13, "slot", 
#nullable restore
#line (23,22)-(23,44) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
FluentSlot.Description

#line default
#line hidden
#nullable disable
            );
#nullable restore
#line (23,47)-(23,58) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
__builder.AddContent(14, Description

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
#nullable restore
#line (24,1)-(25,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/List/FluentOption.razor"
    }

#line default
#line hidden
#nullable disable

            __builder.CloseElement();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
