#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Overlay/FluentOverlay.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "a08006f20901444171b20f7443d1dc41ab986394a2034824b4ecda2c816e69e3"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Overlay/FluentOverlay.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Overlay/FluentOverlay.razor"
using Microsoft.FluentUI.AspNetCore.Components.Extensions

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentOverlay : 
#nullable restore
#line (3,11)-(3,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Overlay/FluentOverlay.razor"
FluentComponentBase

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "fluent-overlay");
            __builder.AddAttribute(1, "id", 
#nullable restore
#line (5,22)-(5,24) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Overlay/FluentOverlay.razor"
Id

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(2, "dialog-style", 
#nullable restore
#line (6,32)-(6,42) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Overlay/FluentOverlay.razor"
StyleValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(3, "dialog-class", 
#nullable restore
#line (7,32)-(7,42) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Overlay/FluentOverlay.razor"
ClassValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(4, "background", 
#nullable restore
#line (8,30)-(8,45) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Overlay/FluentOverlay.razor"
GetBackground()

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(5, "fullscreen", 
#nullable restore
#line (9,30)-(9,40) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Overlay/FluentOverlay.razor"
FullScreen

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(6, "interactive", 
#nullable restore
#line (10,31)-(10,42) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Overlay/FluentOverlay.razor"
Interactive

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(7, "close-mode", 
#nullable restore
#line (11,30)-(11,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Overlay/FluentOverlay.razor"
CloseMode.ToAttributeValue()

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(8, "visible", 
#nullable restore
#line (12,27)-(12,34) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Overlay/FluentOverlay.razor"
Visible

#line default
#line hidden
#nullable disable
            );
            __builder.AddMultipleAttributes(9, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (13,31)-(13,51) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Overlay/FluentOverlay.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(10, "ondialogtoggle", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.FluentUI.AspNetCore.Components.DialogToggleEventArgs>(this, 
#nullable restore
#line (14,35)-(14,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Overlay/FluentOverlay.razor"
OnToggleAsync

#line default
#line hidden
#nullable disable
            ));
#nullable restore
#line (15,1)-(15,5) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Overlay/FluentOverlay.razor"
    

#line default
#line hidden
#nullable disable

#nullable restore
#line (15,6)-(17,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Overlay/FluentOverlay.razor"
if (ChildContent is null)
    {

#line default
#line hidden
#nullable disable

            __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentSpinner>(11);
            __builder.CloseComponent();
#nullable restore
#line (18,1)-(21,9) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Overlay/FluentOverlay.razor"
    }
    else
    {
        

#line default
#line hidden
#nullable disable

#nullable restore
#line (21,10)-(21,22) 25 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Overlay/FluentOverlay.razor"
__builder.AddContent(12, ChildContent

#line default
#line hidden
#nullable disable
            );
#nullable restore
#line (21,22)-(23,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Overlay/FluentOverlay.razor"

    }

#line default
#line hidden
#nullable disable

            __builder.CloseElement();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
