#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "369b2aee06910d3441bcd7d2352f882c2918f5cba3b238c368713e566960d69e"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,59) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
using Microsoft.FluentUI.AspNetCore.Components.Extensions

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentNavCategory : 
#nullable restore
#line (3,11)-(3,24) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
FluentNavBase

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            global::__Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentNavCategory.TypeInference.CreateCascadingValue_0(__builder, 0, 1, "Category", 2, 
#nullable restore
#line (5,40)-(5,44) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
this

#line default
#line hidden
#nullable disable
            , 3, (__builder2) => {
                __builder2.OpenElement(4, "button");
                __builder2.AddAttribute(5, "id", 
#nullable restore
#line (6,15)-(6,17) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
Id

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(6, "tabindex", "-1");
                __builder2.AddAttribute(7, "aria-expanded", 
#nullable restore
#line (8,20)-(8,49) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
Expanded.ToString().ToLower()

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(8, "class", 
#nullable restore
#line (9,12)-(9,22) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
ClassValue

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(9, "style", 
#nullable restore
#line (10,12)-(10,22) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
StyleValue

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(10, "title", 
#nullable restore
#line (11,13)-(11,29) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
Tooltip ?? Title

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(11, "onclick", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (12,14)-(12,33) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
ToggleExpandedAsync

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddMultipleAttributes(12, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (13,18)-(13,38) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
                ));
#nullable restore
#line (14,1)-(14,3) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
		

#line default
#line hidden
#nullable disable

#nullable restore
#line (14,4)-(17,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
if (Owner.UseIcons && IconRest is not null)
		{
            var customColor = _isActive ? (IconActive?.Color ?? IconRest.Color) : IconRest.Color;

#line default
#line hidden
#nullable disable

                global::__Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentNavCategory.TypeInference.CreateFluentIcon_1(__builder2, 13, 14, 
#nullable restore
#line (17,25)-(17,70) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
_isActive ? IconActive ?? IconRest : IconRest

#line default
#line hidden
#nullable disable
                , 15, "icon", 16, 
#nullable restore
#line (17,95)-(19,71) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
_isActive
                ? (customColor != null ? Color.Custom : Color.Primary)
                : (customColor != null ? Color.Custom : Color.Default)

#line default
#line hidden
#nullable disable
                , 17, 
#nullable restore
#line (19,89)-(19,100) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
customColor

#line default
#line hidden
#nullable disable
                );
#nullable restore
#line (20,1)-(21,1) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
		}

#line default
#line hidden
#nullable disable

#nullable restore
#line (21,4)-(21,9) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
__builder2.AddContent(18, Title

#line default
#line hidden
#nullable disable
                );
                __builder2.AddMarkupContent(19, "\n\t\t");
                __builder2.OpenElement(20, "span");
                __builder2.AddAttribute(21, "aria-hidden", "true");
                __builder2.AddAttribute(22, "class", 
#nullable restore
#line (22,37)-(22,140) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
 "expand-icon" + (Expanded ? " expanded" : "") + (_hasBeenManuallyCollapsed ? " user-interacted" : "") 

#line default
#line hidden
#nullable disable
                );
                global::__Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentNavCategory.TypeInference.CreateFluentIcon_2(__builder2, 23, 24, 
#nullable restore
#line (23,25)-(23,67) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
new CoreIcons.Regular.Size20.ChevronDown()

#line default
#line hidden
#nullable disable
                );
                __builder2.CloseElement();
                __builder2.CloseElement();
                __builder2.AddMarkupContent(25, "\n\t");
                __builder2.OpenElement(26, "div");
                __builder2.AddAttribute(27, "id", 
#nullable restore
#line (26,13)-(26,26) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
$"{Id}-group"

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(28, "class", 
#nullable restore
#line (27,13)-(27,127) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
 "fluent-navsubitemgroup" + (Expanded ? " expanded" : "") + (_hasBeenManuallyCollapsed ? " user-interacted" : "") 

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(29, "style", 
#nullable restore
#line (28,12)-(28,34) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
GetSubitemGroupStyle()

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(30, "expanded", 
#nullable restore
#line (29,15)-(29,23) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
Expanded

#line default
#line hidden
#nullable disable
                );
                __builder2.AddAttribute(31, "aria-hidden", 
#nullable restore
#line (30,19)-(30,28) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
!Expanded

#line default
#line hidden
#nullable disable
                );
#nullable restore
#line (31,4)-(31,16) 26 "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
__builder2.AddContent(32, ChildContent

#line default
#line hidden
#nullable disable
                );
                __builder2.CloseElement();
            }
            );
        }
        #pragma warning restore 1998
    }
}
namespace __Blazor.Microsoft.FluentUI.AspNetCore.Components.FluentNavCategory
{
    #line hidden
    internal static class TypeInference
    {
        public static void CreateCascadingValue_0<TValue>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, global::System.String __arg0, int __seq1, TValue __arg1, int __seq2, global::Microsoft.AspNetCore.Components.RenderFragment __arg2)
        {
        __builder.OpenComponent<global::Microsoft.AspNetCore.Components.CascadingValue<TValue>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::Microsoft.AspNetCore.Components.CascadingValue<TValue>.
#nullable restore
#line (5,17)-(5,21) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
Name

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::Microsoft.AspNetCore.Components.CascadingValue<TValue>.
#nullable restore
#line (5,33)-(5,38) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, "ChildContent", __arg2);
        __builder.CloseComponent();
        }
        public static void CreateFluentIcon_1<Icon>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, Icon __arg0, int __seq1, global::System.String __arg1, int __seq2, global::Microsoft.FluentUI.AspNetCore.Components.Color? __arg2, int __seq3, global::System.String __arg3)
            where Icon : global::Microsoft.FluentUI.AspNetCore.Components.Icon, new()
        {
        __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (17,16)-(17,21) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (17,73)-(17,78) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
Class

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (17,86)-(17,91) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
Color

#line default
#line hidden
#nullable disable
        ), __arg2);
        __builder.AddComponentParameter(__seq3, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (19,74)-(19,85) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
CustomColor

#line default
#line hidden
#nullable disable
        ), __arg3);
        __builder.CloseComponent();
        }
        public static void CreateFluentIcon_2<Icon>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, Icon __arg0)
            where Icon : global::Microsoft.FluentUI.AspNetCore.Components.Icon, new()
        {
        __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::Microsoft.FluentUI.AspNetCore.Components.FluentIcon<Icon>.
#nullable restore
#line (23,16)-(23,21) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Components/Nav/FluentNavCategory.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.CloseComponent();
        }
    }
}
#pragma warning restore 1591
