#pragma checksum "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Infrastructure/FluentProviders.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "96b1d2c1b2f111bfe27a5fd49f79f93cbb27eea79b2d10a7271608b7aba8313b"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,52) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Infrastructure/FluentProviders.razor"
Microsoft.FluentUI.AspNetCore.Components

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
#nullable restore
#line (1,2)-(1,14) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using System.Diagnostics.CodeAnalysis

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,39) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,48) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,58) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.FluentUI.AspNetCore.Components.Utilities

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,27) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class FluentProviders : 
#nullable restore
#line (2,11)-(2,30) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Infrastructure/FluentProviders.razor"
FluentComponentBase

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "id", 
#nullable restore
#line (4,11)-(4,13) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Infrastructure/FluentProviders.razor"
Id

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(2, "class", 
#nullable restore
#line (4,23)-(4,33) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Infrastructure/FluentProviders.razor"
ClassValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(3, "style", 
#nullable restore
#line (4,43)-(4,53) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Infrastructure/FluentProviders.razor"
StyleValue

#line default
#line hidden
#nullable disable
            );
            __builder.AddMultipleAttributes(4, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>>(
#nullable restore
#line (4,68)-(4,88) "/home/llm/Git/Esi.AI/origins/sidatacom/fluentui-blazor/src/Core/Infrastructure/FluentProviders.razor"
AdditionalAttributes

#line default
#line hidden
#nullable disable
            ));
            __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentDialogProvider>(5);
            __builder.CloseComponent();
            __builder.AddMarkupContent(6, "\n    ");
            __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentToastProvider>(7);
            __builder.CloseComponent();
            __builder.AddMarkupContent(8, "\n    ");
            __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentTooltipProvider>(9);
            __builder.CloseComponent();
            __builder.AddMarkupContent(10, "\n    ");
            __builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentKeyCodeProvider>(11);
            __builder.CloseComponent();
            __builder.CloseElement();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
