// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Microsoft.FluentUI.AspNetCore.Components.Charts
{
    internal sealed partial class AreaChartDataJsonSerializerContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.IReadOnlyList<global::Microsoft.FluentUI.AspNetCore.Components.Charts.AreaChartSeries>>? _IReadOnlyListAreaChartSeries;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.IReadOnlyList<global::Microsoft.FluentUI.AspNetCore.Components.Charts.AreaChartSeries>> IReadOnlyListAreaChartSeries
        {
            get => _IReadOnlyListAreaChartSeries ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.IReadOnlyList<global::Microsoft.FluentUI.AspNetCore.Components.Charts.AreaChartSeries>>)Options.GetTypeInfo(typeof(global::System.Collections.Generic.IReadOnlyList<global::Microsoft.FluentUI.AspNetCore.Components.Charts.AreaChartSeries>));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.IReadOnlyList<global::Microsoft.FluentUI.AspNetCore.Components.Charts.AreaChartSeries>> Create_IReadOnlyListAreaChartSeries(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::System.Collections.Generic.IReadOnlyList<global::Microsoft.FluentUI.AspNetCore.Components.Charts.AreaChartSeries>>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.IReadOnlyList<global::Microsoft.FluentUI.AspNetCore.Components.Charts.AreaChartSeries>> jsonTypeInfo))
            {
                var info = new global::System.Text.Json.Serialization.Metadata.JsonCollectionInfoValues<global::System.Collections.Generic.IReadOnlyList<global::Microsoft.FluentUI.AspNetCore.Components.Charts.AreaChartSeries>>
                {
                    ObjectCreator = null,
                    SerializeHandler = IReadOnlyListAreaChartSeriesSerializeHandler
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateIEnumerableInfo<global::System.Collections.Generic.IReadOnlyList<global::Microsoft.FluentUI.AspNetCore.Components.Charts.AreaChartSeries>, global::Microsoft.FluentUI.AspNetCore.Components.Charts.AreaChartSeries>(options, info);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void IReadOnlyListAreaChartSeriesSerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::System.Collections.Generic.IReadOnlyList<global::Microsoft.FluentUI.AspNetCore.Components.Charts.AreaChartSeries>? value)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartArray();

            foreach (global::Microsoft.FluentUI.AspNetCore.Components.Charts.AreaChartSeries element in value)
            {
                AreaChartSeriesSerializeHandler(writer, element);
            }

            writer.WriteEndArray();
        }
    }
}
