// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Microsoft.FluentUI.AspNetCore.Components
{
    public sealed partial class FluentUIJsonSerializerContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.KeyPress>? _KeyPress;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.KeyPress> KeyPress
        {
            get => _KeyPress ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.KeyPress>)Options.GetTypeInfo(typeof(global::Microsoft.FluentUI.AspNetCore.Components.KeyPress));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.KeyPress> Create_KeyPress(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::Microsoft.FluentUI.AspNetCore.Components.KeyPress>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.KeyPress> jsonTypeInfo))
            {
                var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Microsoft.FluentUI.AspNetCore.Components.KeyPress>
                {
                    ObjectCreator = null,
                    ObjectWithParameterizedConstructorCreator = static args => new global::Microsoft.FluentUI.AspNetCore.Components.KeyPress(){ Key = (global::Microsoft.FluentUI.AspNetCore.Components.KeyCode)args[0], CtrlKey = (bool)args[1], ShiftKey = (bool)args[2], AltKey = (bool)args[3], MetaKey = (bool)args[4], PreventDefault = (bool)args[5] },
                    PropertyMetadataInitializer = _ => KeyPressPropInit(options),
                    ConstructorParameterMetadataInitializer = KeyPressCtorParamInit,
                    SerializeHandler = KeyPressSerializeHandler
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Microsoft.FluentUI.AspNetCore.Components.KeyPress>(options, objectInfo);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[] KeyPressPropInit(global::System.Text.Json.JsonSerializerOptions options)
        {
            var properties = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[6];

            var info0 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Microsoft.FluentUI.AspNetCore.Components.KeyCode>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.KeyPress),
                Converter = null,
                Getter = static obj => ((global::Microsoft.FluentUI.AspNetCore.Components.KeyPress)obj).Key,
                Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting init-only properties is not supported in source generation mode."),
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Key",
                JsonPropertyName = null
            };
            
            properties[0] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Microsoft.FluentUI.AspNetCore.Components.KeyCode>(options, info0);

            var info1 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<bool>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.KeyPress),
                Converter = null,
                Getter = static obj => ((global::Microsoft.FluentUI.AspNetCore.Components.KeyPress)obj).CtrlKey,
                Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting init-only properties is not supported in source generation mode."),
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "CtrlKey",
                JsonPropertyName = null
            };
            
            properties[1] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<bool>(options, info1);

            var info2 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<bool>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.KeyPress),
                Converter = null,
                Getter = static obj => ((global::Microsoft.FluentUI.AspNetCore.Components.KeyPress)obj).ShiftKey,
                Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting init-only properties is not supported in source generation mode."),
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "ShiftKey",
                JsonPropertyName = null
            };
            
            properties[2] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<bool>(options, info2);

            var info3 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<bool>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.KeyPress),
                Converter = null,
                Getter = static obj => ((global::Microsoft.FluentUI.AspNetCore.Components.KeyPress)obj).AltKey,
                Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting init-only properties is not supported in source generation mode."),
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "AltKey",
                JsonPropertyName = null
            };
            
            properties[3] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<bool>(options, info3);

            var info4 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<bool>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.KeyPress),
                Converter = null,
                Getter = static obj => ((global::Microsoft.FluentUI.AspNetCore.Components.KeyPress)obj).MetaKey,
                Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting init-only properties is not supported in source generation mode."),
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "MetaKey",
                JsonPropertyName = null
            };
            
            properties[4] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<bool>(options, info4);

            var info5 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<bool>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.KeyPress),
                Converter = null,
                Getter = static obj => ((global::Microsoft.FluentUI.AspNetCore.Components.KeyPress)obj).PreventDefault,
                Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting init-only properties is not supported in source generation mode."),
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "PreventDefault",
                JsonPropertyName = null
            };
            
            properties[5] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<bool>(options, info5);

            return properties;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void KeyPressSerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::Microsoft.FluentUI.AspNetCore.Components.KeyPress? value)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();

            writer.WritePropertyName(PropName_key);
            global::System.Text.Json.JsonSerializer.Serialize(writer, ((global::Microsoft.FluentUI.AspNetCore.Components.KeyPress)value).Key, KeyCode);
            writer.WriteBoolean(PropName_ctrlKey, ((global::Microsoft.FluentUI.AspNetCore.Components.KeyPress)value).CtrlKey);
            writer.WriteBoolean(PropName_shiftKey, ((global::Microsoft.FluentUI.AspNetCore.Components.KeyPress)value).ShiftKey);
            writer.WriteBoolean(PropName_altKey, ((global::Microsoft.FluentUI.AspNetCore.Components.KeyPress)value).AltKey);
            writer.WriteBoolean(PropName_metaKey, ((global::Microsoft.FluentUI.AspNetCore.Components.KeyPress)value).MetaKey);
            writer.WriteBoolean(PropName_preventDefault, ((global::Microsoft.FluentUI.AspNetCore.Components.KeyPress)value).PreventDefault);

            writer.WriteEndObject();
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[] KeyPressCtorParamInit()
        {
            var parameters = new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[6];

            parameters[0] = new()
            {
                Name = "Key",
                ParameterType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.KeyCode),
                Position = 0,
            };
            
            parameters[1] = new()
            {
                Name = "CtrlKey",
                ParameterType = typeof(bool),
                Position = 1,
            };
            
            parameters[2] = new()
            {
                Name = "ShiftKey",
                ParameterType = typeof(bool),
                Position = 2,
            };
            
            parameters[3] = new()
            {
                Name = "AltKey",
                ParameterType = typeof(bool),
                Position = 3,
            };
            
            parameters[4] = new()
            {
                Name = "MetaKey",
                ParameterType = typeof(bool),
                Position = 4,
            };
            
            parameters[5] = new()
            {
                Name = "PreventDefault",
                ParameterType = typeof(bool),
                Position = 5,
            };
            
            return parameters;
        }
    }
}
