// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Microsoft.FluentUI.AspNetCore.Components
{
    public sealed partial class FluentUIJsonSerializerContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs>? _MenuItemEventArgs;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs> MenuItemEventArgs
        {
            get => _MenuItemEventArgs ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs>)Options.GetTypeInfo(typeof(global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs> Create_MenuItemEventArgs(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs> jsonTypeInfo))
            {
                var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs>
                {
                    ObjectCreator = null,
                    ObjectWithParameterizedConstructorCreator = static args => new global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs(){ Id = (string)args[0], Checked = (bool?)args[1], Text = (string)args[2] },
                    PropertyMetadataInitializer = _ => MenuItemEventArgsPropInit(options),
                    ConstructorParameterMetadataInitializer = MenuItemEventArgsCtorParamInit,
                    SerializeHandler = MenuItemEventArgsSerializeHandler
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs>(options, objectInfo);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[] MenuItemEventArgsPropInit(global::System.Text.Json.JsonSerializerOptions options)
        {
            var properties = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[4];

            var info0 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<string>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs),
                Converter = null,
                Getter = static obj => ((global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs)obj).Id,
                Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting init-only properties is not supported in source generation mode."),
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Id",
                JsonPropertyName = null
            };
            
            properties[0] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, info0);

            var info1 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Microsoft.FluentUI.AspNetCore.Components.FluentMenuItem>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs),
                Converter = null,
                Getter = null,
                Setter = null,
                IgnoreCondition = global::System.Text.Json.Serialization.JsonIgnoreCondition.Always,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Item",
                JsonPropertyName = null
            };
            
            properties[1] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Microsoft.FluentUI.AspNetCore.Components.FluentMenuItem>(options, info1);

            var info2 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<bool?>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs),
                Converter = null,
                Getter = static obj => ((global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs)obj).Checked,
                Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting init-only properties is not supported in source generation mode."),
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Checked",
                JsonPropertyName = null
            };
            
            properties[2] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<bool?>(options, info2);

            var info3 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<string>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs),
                Converter = null,
                Getter = static obj => ((global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs)obj).Text,
                Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting init-only properties is not supported in source generation mode."),
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Text",
                JsonPropertyName = null
            };
            
            properties[3] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, info3);

            return properties;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void MenuItemEventArgsSerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs? value)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();

            writer.WriteString(PropName_id, ((global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs)value).Id);
            writer.WritePropertyName(PropName_checked);
            global::System.Text.Json.JsonSerializer.Serialize(writer, ((global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs)value).Checked, NullableBoolean);
            writer.WriteString(PropName_text, ((global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs)value).Text);

            writer.WriteEndObject();
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[] MenuItemEventArgsCtorParamInit()
        {
            var parameters = new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[3];

            parameters[0] = new()
            {
                Name = "Id",
                ParameterType = typeof(string),
                Position = 0,
            };
            
            parameters[1] = new()
            {
                Name = "Checked",
                ParameterType = typeof(bool?),
                Position = 1,
            };
            
            parameters[2] = new()
            {
                Name = "Text",
                ParameterType = typeof(string),
                Position = 2,
            };
            
            return parameters;
        }
    }
}
