// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Microsoft.FluentUI.AspNetCore.Components
{
    public sealed partial class FluentUIJsonSerializerContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.TreeItemToggleEventArgs>? _TreeItemToggleEventArgs;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.TreeItemToggleEventArgs> TreeItemToggleEventArgs
        {
            get => _TreeItemToggleEventArgs ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.TreeItemToggleEventArgs>)Options.GetTypeInfo(typeof(global::Microsoft.FluentUI.AspNetCore.Components.TreeItemToggleEventArgs));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.TreeItemToggleEventArgs> Create_TreeItemToggleEventArgs(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::Microsoft.FluentUI.AspNetCore.Components.TreeItemToggleEventArgs>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.TreeItemToggleEventArgs> jsonTypeInfo))
            {
                var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Microsoft.FluentUI.AspNetCore.Components.TreeItemToggleEventArgs>
                {
                    ObjectCreator = () => new global::Microsoft.FluentUI.AspNetCore.Components.TreeItemToggleEventArgs(),
                    ObjectWithParameterizedConstructorCreator = null,
                    PropertyMetadataInitializer = _ => TreeItemToggleEventArgsPropInit(options),
                    ConstructorParameterMetadataInitializer = null,
                    SerializeHandler = TreeItemToggleEventArgsSerializeHandler
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Microsoft.FluentUI.AspNetCore.Components.TreeItemToggleEventArgs>(options, objectInfo);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[] TreeItemToggleEventArgsPropInit(global::System.Text.Json.JsonSerializerOptions options)
        {
            var properties = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[4];

            var info0 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<string>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.DialogToggleEventArgs),
                Converter = null,
                Getter = static obj => ((global::Microsoft.FluentUI.AspNetCore.Components.DialogToggleEventArgs)obj).Id,
                Setter = static (obj, value) => ((global::Microsoft.FluentUI.AspNetCore.Components.DialogToggleEventArgs)obj).Id = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Id",
                JsonPropertyName = null
            };
            
            properties[0] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, info0);

            var info1 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<string>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.DialogToggleEventArgs),
                Converter = null,
                Getter = static obj => ((global::Microsoft.FluentUI.AspNetCore.Components.DialogToggleEventArgs)obj).OldState,
                Setter = static (obj, value) => ((global::Microsoft.FluentUI.AspNetCore.Components.DialogToggleEventArgs)obj).OldState = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "OldState",
                JsonPropertyName = null
            };
            
            properties[1] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, info1);

            var info2 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<string>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.DialogToggleEventArgs),
                Converter = null,
                Getter = static obj => ((global::Microsoft.FluentUI.AspNetCore.Components.DialogToggleEventArgs)obj).NewState,
                Setter = static (obj, value) => ((global::Microsoft.FluentUI.AspNetCore.Components.DialogToggleEventArgs)obj).NewState = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "NewState",
                JsonPropertyName = null
            };
            
            properties[2] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, info2);

            var info3 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<string>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.DialogToggleEventArgs),
                Converter = null,
                Getter = static obj => ((global::Microsoft.FluentUI.AspNetCore.Components.DialogToggleEventArgs)obj).Type,
                Setter = static (obj, value) => ((global::Microsoft.FluentUI.AspNetCore.Components.DialogToggleEventArgs)obj).Type = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Type",
                JsonPropertyName = null
            };
            
            properties[3] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, info3);

            return properties;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void TreeItemToggleEventArgsSerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::Microsoft.FluentUI.AspNetCore.Components.TreeItemToggleEventArgs? value)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();

            writer.WriteString(PropName_id, ((global::Microsoft.FluentUI.AspNetCore.Components.DialogToggleEventArgs)value).Id);
            writer.WriteString(PropName_oldState, ((global::Microsoft.FluentUI.AspNetCore.Components.DialogToggleEventArgs)value).OldState);
            writer.WriteString(PropName_newState, ((global::Microsoft.FluentUI.AspNetCore.Components.DialogToggleEventArgs)value).NewState);
            writer.WriteString(PropName_type, ((global::Microsoft.FluentUI.AspNetCore.Components.DialogToggleEventArgs)value).Type);

            writer.WriteEndObject();
        }
    }
}
