// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Microsoft.FluentUI.AspNetCore.Components
{
    public sealed partial class FluentUIJsonSerializerContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.OverflowBehavior?>? _NullableOverflowBehavior;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.OverflowBehavior?> NullableOverflowBehavior
        {
            get => _NullableOverflowBehavior ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.OverflowBehavior?>)Options.GetTypeInfo(typeof(global::Microsoft.FluentUI.AspNetCore.Components.OverflowBehavior?));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.OverflowBehavior?> Create_NullableOverflowBehavior(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::Microsoft.FluentUI.AspNetCore.Components.OverflowBehavior?>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.OverflowBehavior?> jsonTypeInfo))
            {
                global::System.Text.Json.Serialization.JsonConverter converter = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.GetNullableConverter<global::Microsoft.FluentUI.AspNetCore.Components.OverflowBehavior>(options);
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<global::Microsoft.FluentUI.AspNetCore.Components.OverflowBehavior?>(options, converter);
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }
    }
}
