// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Microsoft.FluentUI.AspNetCore.Components
{
    public sealed partial class FluentUIJsonSerializerContext : global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver
    {
        /// <inheritdoc/>
        public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type)
        {
            Options.TryGetTypeInfo(type, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? typeInfo);
            return typeInfo;
        }

        global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
        {
            if (type == typeof(bool))
            {
                return Create_Boolean(options);
            }
            if (type == typeof(bool?))
            {
                return Create_NullableBoolean(options);
            }
            if (type == typeof(double))
            {
                return Create_Double(options);
            }
            if (type == typeof(global::Microsoft.FluentUI.AspNetCore.Components.AccordionItemEventArgs))
            {
                return Create_AccordionItemEventArgs(options);
            }
            if (type == typeof(global::Microsoft.FluentUI.AspNetCore.Components.DialogToggleEventArgs))
            {
                return Create_DialogToggleEventArgs(options);
            }
            if (type == typeof(global::Microsoft.FluentUI.AspNetCore.Components.DropdownEventArgs))
            {
                return Create_DropdownEventArgs(options);
            }
            if (type == typeof(global::Microsoft.FluentUI.AspNetCore.Components.KeyCode))
            {
                return Create_KeyCode(options);
            }
            if (type == typeof(global::Microsoft.FluentUI.AspNetCore.Components.KeyPress))
            {
                return Create_KeyPress(options);
            }
            if (type == typeof(global::Microsoft.FluentUI.AspNetCore.Components.KeyPress[]))
            {
                return Create_KeyPressArray(options);
            }
            if (type == typeof(global::Microsoft.FluentUI.AspNetCore.Components.MenuItemEventArgs))
            {
                return Create_MenuItemEventArgs(options);
            }
            if (type == typeof(global::Microsoft.FluentUI.AspNetCore.Components.OverflowBehavior))
            {
                return Create_OverflowBehavior(options);
            }
            if (type == typeof(global::Microsoft.FluentUI.AspNetCore.Components.OverflowBehavior?))
            {
                return Create_NullableOverflowBehavior(options);
            }
            if (type == typeof(global::Microsoft.FluentUI.AspNetCore.Components.OverflowChangedEventArgs))
            {
                return Create_OverflowChangedEventArgs(options);
            }
            if (type == typeof(global::Microsoft.FluentUI.AspNetCore.Components.OverflowChangedItem))
            {
                return Create_OverflowChangedItem(options);
            }
            if (type == typeof(global::Microsoft.FluentUI.AspNetCore.Components.RadioEventArgs))
            {
                return Create_RadioEventArgs(options);
            }
            if (type == typeof(global::Microsoft.FluentUI.AspNetCore.Components.TabChangeEventArgs))
            {
                return Create_TabChangeEventArgs(options);
            }
            if (type == typeof(global::Microsoft.FluentUI.AspNetCore.Components.TreeItemChangedEventArgs))
            {
                return Create_TreeItemChangedEventArgs(options);
            }
            if (type == typeof(global::Microsoft.FluentUI.AspNetCore.Components.TreeItemToggleEventArgs))
            {
                return Create_TreeItemToggleEventArgs(options);
            }
            if (type == typeof(global::System.Collections.Generic.Dictionary<string, object>))
            {
                return Create_DictionaryStringObject(options);
            }
            if (type == typeof(global::System.Collections.Generic.IReadOnlyList<global::Microsoft.FluentUI.AspNetCore.Components.OverflowChangedItem>))
            {
                return Create_IReadOnlyListOverflowChangedItem(options);
            }
            if (type == typeof(global::System.Collections.Generic.IReadOnlyList<string>))
            {
                return Create_IReadOnlyListString(options);
            }
            if (type == typeof(int))
            {
                return Create_Int32(options);
            }
            if (type == typeof(object))
            {
                return Create_Object(options);
            }
            if (type == typeof(string))
            {
                return Create_String(options);
            }
            return null;
        }
    }
}
