// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Microsoft.FluentUI.AspNetCore.Components.Charts
{
    internal sealed partial class FunnelChartDataJsonSerializerContext : global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver
    {
        /// <inheritdoc/>
        public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type)
        {
            Options.TryGetTypeInfo(type, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? typeInfo);
            return typeInfo;
        }

        global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
        {
            if (type == typeof(double))
            {
                return Create_Double(options);
            }
            if (type == typeof(global::Microsoft.FluentUI.AspNetCore.Components.Charts.FunnelDataPoint))
            {
                return Create_FunnelDataPoint(options);
            }
            if (type == typeof(global::Microsoft.FluentUI.AspNetCore.Components.Charts.FunnelSubValue))
            {
                return Create_FunnelSubValue(options);
            }
            if (type == typeof(global::System.Collections.Generic.IReadOnlyList<global::Microsoft.FluentUI.AspNetCore.Components.Charts.FunnelDataPoint>))
            {
                return Create_IReadOnlyListFunnelDataPoint(options);
            }
            if (type == typeof(global::System.Collections.Generic.IReadOnlyList<global::Microsoft.FluentUI.AspNetCore.Components.Charts.FunnelSubValue>))
            {
                return Create_IReadOnlyListFunnelSubValue(options);
            }
            if (type == typeof(string))
            {
                return Create_String(options);
            }
            return null;
        }
    }
}
