// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Microsoft.FluentUI.AspNetCore.Components.Charts
{
    internal sealed partial class HorizontalBarChartDataJsonSerializerContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries>? _HorizontalBarChartSeries;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries> HorizontalBarChartSeries
        {
            get => _HorizontalBarChartSeries ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries>)Options.GetTypeInfo(typeof(global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries> Create_HorizontalBarChartSeries(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries> jsonTypeInfo))
            {
                var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries>
                {
                    ObjectCreator = null,
                    ObjectWithParameterizedConstructorCreator = static args => new global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries(){ ChartSeriesTitle = (string)args[0], ChartData = (global::System.Collections.Generic.IReadOnlyList<global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartDataPoint>)args[1], BenchmarkData = (double?)args[2], ChartDataText = (string)args[3] },
                    PropertyMetadataInitializer = _ => HorizontalBarChartSeriesPropInit(options),
                    ConstructorParameterMetadataInitializer = HorizontalBarChartSeriesCtorParamInit,
                    SerializeHandler = HorizontalBarChartSeriesSerializeHandler
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries>(options, objectInfo);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[] HorizontalBarChartSeriesPropInit(global::System.Text.Json.JsonSerializerOptions options)
        {
            var properties = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[4];

            var info0 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<string>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries),
                Converter = null,
                Getter = static obj => ((global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries)obj).ChartSeriesTitle,
                Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting init-only properties is not supported in source generation mode."),
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "ChartSeriesTitle",
                JsonPropertyName = "chartSeriesTitle"
            };
            
            properties[0] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, info0);

            var info1 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::System.Collections.Generic.IReadOnlyList<global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartDataPoint>>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries),
                Converter = null,
                Getter = static obj => ((global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries)obj).ChartData,
                Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting init-only properties is not supported in source generation mode."),
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "ChartData",
                JsonPropertyName = "chartData"
            };
            
            properties[1] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Collections.Generic.IReadOnlyList<global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartDataPoint>>(options, info1);

            var info2 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<double?>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries),
                Converter = null,
                Getter = static obj => ((global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries)obj).BenchmarkData,
                Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting init-only properties is not supported in source generation mode."),
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "BenchmarkData",
                JsonPropertyName = "benchmarkData"
            };
            
            properties[2] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<double?>(options, info2);

            var info3 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<string>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries),
                Converter = null,
                Getter = static obj => ((global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries)obj).ChartDataText,
                Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting init-only properties is not supported in source generation mode."),
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "ChartDataText",
                JsonPropertyName = "chartDataText"
            };
            
            properties[3] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, info3);

            return properties;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void HorizontalBarChartSeriesSerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries? value)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();

            writer.WriteString(PropName_chartSeriesTitle, ((global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries)value).ChartSeriesTitle);
            writer.WritePropertyName(PropName_chartData);
            IReadOnlyListHorizontalBarChartDataPointSerializeHandler(writer, ((global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries)value).ChartData);
            writer.WritePropertyName(PropName_benchmarkData);
            global::System.Text.Json.JsonSerializer.Serialize(writer, ((global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries)value).BenchmarkData, NullableDouble);
            writer.WriteString(PropName_chartDataText, ((global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartSeries)value).ChartDataText);

            writer.WriteEndObject();
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[] HorizontalBarChartSeriesCtorParamInit()
        {
            var parameters = new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[4];

            parameters[0] = new()
            {
                Name = "ChartSeriesTitle",
                ParameterType = typeof(string),
                Position = 0,
            };
            
            parameters[1] = new()
            {
                Name = "ChartData",
                ParameterType = typeof(global::System.Collections.Generic.IReadOnlyList<global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartDataPoint>),
                Position = 1,
            };
            
            parameters[2] = new()
            {
                Name = "BenchmarkData",
                ParameterType = typeof(double?),
                Position = 2,
            };
            
            parameters[3] = new()
            {
                Name = "ChartDataText",
                ParameterType = typeof(string),
                Position = 3,
            };
            
            return parameters;
        }
    }
}
