// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Microsoft.FluentUI.AspNetCore.Components.Charts
{
    internal sealed partial class HorizontalBarChartWithAxisDataJsonSerializerContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.Charts.CalloutAccessibilityData>? _CalloutAccessibilityData;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.Charts.CalloutAccessibilityData> CalloutAccessibilityData
        {
            get => _CalloutAccessibilityData ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.Charts.CalloutAccessibilityData>)Options.GetTypeInfo(typeof(global::Microsoft.FluentUI.AspNetCore.Components.Charts.CalloutAccessibilityData));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.Charts.CalloutAccessibilityData> Create_CalloutAccessibilityData(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::Microsoft.FluentUI.AspNetCore.Components.Charts.CalloutAccessibilityData>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.FluentUI.AspNetCore.Components.Charts.CalloutAccessibilityData> jsonTypeInfo))
            {
                var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Microsoft.FluentUI.AspNetCore.Components.Charts.CalloutAccessibilityData>
                {
                    ObjectCreator = null,
                    ObjectWithParameterizedConstructorCreator = static args => new global::Microsoft.FluentUI.AspNetCore.Components.Charts.CalloutAccessibilityData(){ AriaLabel = (string)args[0] },
                    PropertyMetadataInitializer = _ => CalloutAccessibilityDataPropInit(options),
                    ConstructorParameterMetadataInitializer = CalloutAccessibilityDataCtorParamInit,
                    SerializeHandler = CalloutAccessibilityDataSerializeHandler
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Microsoft.FluentUI.AspNetCore.Components.Charts.CalloutAccessibilityData>(options, objectInfo);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[] CalloutAccessibilityDataPropInit(global::System.Text.Json.JsonSerializerOptions options)
        {
            var properties = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[1];

            var info0 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<string>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Microsoft.FluentUI.AspNetCore.Components.Charts.CalloutAccessibilityData),
                Converter = null,
                Getter = static obj => ((global::Microsoft.FluentUI.AspNetCore.Components.Charts.CalloutAccessibilityData)obj).AriaLabel,
                Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting init-only properties is not supported in source generation mode."),
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "AriaLabel",
                JsonPropertyName = "ariaLabel"
            };
            
            properties[0] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, info0);

            return properties;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void CalloutAccessibilityDataSerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::Microsoft.FluentUI.AspNetCore.Components.Charts.CalloutAccessibilityData? value)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();

            writer.WriteString(PropName_ariaLabel, ((global::Microsoft.FluentUI.AspNetCore.Components.Charts.CalloutAccessibilityData)value).AriaLabel);

            writer.WriteEndObject();
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[] CalloutAccessibilityDataCtorParamInit()
        {
            var parameters = new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[1];

            parameters[0] = new()
            {
                Name = "AriaLabel",
                ParameterType = typeof(string),
                Position = 0,
            };
            
            return parameters;
        }
    }
}
