// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Microsoft.FluentUI.AspNetCore.Components.Charts
{
    internal sealed partial class HorizontalBarChartWithAxisDataJsonSerializerContext : global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver
    {
        /// <inheritdoc/>
        public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type)
        {
            Options.TryGetTypeInfo(type, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? typeInfo);
            return typeInfo;
        }

        global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
        {
            if (type == typeof(double))
            {
                return Create_Double(options);
            }
            if (type == typeof(global::Microsoft.FluentUI.AspNetCore.Components.Charts.CalloutAccessibilityData))
            {
                return Create_CalloutAccessibilityData(options);
            }
            if (type == typeof(global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartWithAxisDataPoint))
            {
                return Create_HorizontalBarChartWithAxisDataPoint(options);
            }
            if (type == typeof(global::System.Collections.Generic.IReadOnlyList<global::Microsoft.FluentUI.AspNetCore.Components.Charts.HorizontalBarChartWithAxisDataPoint>))
            {
                return Create_IReadOnlyListHorizontalBarChartWithAxisDataPoint(options);
            }
            if (type == typeof(string))
            {
                return Create_String(options);
            }
            if (type == typeof(string[]))
            {
                return Create_StringArray(options);
            }
            return null;
        }
    }
}
