<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ServerSideBlazor>true</ServerSideBlazor>
	</PropertyGroup>

	<ItemGroup>
                <ProjectReference Include="..\Esi.AI.Llm\Esi.AI.Llm.csproj" />
	</ItemGroup>

</Project>
