<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Esi.RAG\Esi.RAG.Application\Esi.RAG.Application.csproj" />
    <ProjectReference Include="..\..\src\Esi.RAG\Esi.RAG.Domain\Esi.RAG.Domain.csproj" />
    <ProjectReference Include="..\..\src\Esi.RAG\Esi.RAG.Infrastructure\Esi.RAG.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Esi.RAG\Esi.RAG.Ingestion\Esi.RAG.Ingestion.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" VersionOverride="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" VersionOverride="17.14.1" />
    <PackageReference Include="xunit" VersionOverride="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" VersionOverride="3.1.4" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>